AD_BANK = [
    (1, "Food & Beverage", "Flavor That Moves You"),
    (2, "Food & Beverage", "Freshness Redefined"),
    (3, "Food & Beverage", "Taste the Bright Side"),
    (4, "Food & Beverage", "Naturally Yours"),
    (5, "Food & Beverage", "Pure Goodness Inside"),
    (6, "Food & Beverage", "Beyond the Bite"),
    (7, "Food & Beverage", "Farm to Flavor"),
    (8, "Food & Beverage", "The Joy of Taste"),
    (9, "Food & Beverage", "Sip the Sunshine"),
    (10, "Food & Beverage", "Fresh Every Moment"),
    (11, "Food & Beverage", "Delicious by Design"),
    (12, "Food & Beverage", "Boldly Brewed"),
    (13, "Food & Beverage", "Taste Without Limits"),
    (14, "Food & Beverage", "The Snack Revolution"),
    (15, "Food & Beverage", "Cheers to Better Days"),
    (16, "Food & Beverage", "Flavor in Every Crunch"),
    (17, "Food & Beverage", "Better Bites, Better Life"),
    (18, "Food & Beverage", "From Seed to Savor"),
    (19, "Food & Beverage", "Energy That Lasts"),
    (20, "Food & Beverage", "Crafted with Care"),
    (21, "Home & Lifestyle Goods", "Comfort in Every Corner"),
    (22, "Home & Lifestyle Goods", "Style Meets Simplicity"),
    (23, "Home & Lifestyle Goods", "Living Made Lovely"),
    (24, "Home & Lifestyle Goods", "Designed for Daily Joy"),
    (25, "Home & Lifestyle Goods", "Home, Perfected"),
    (26, "Home & Lifestyle Goods", "Crafted for Life"),
    (27, "Home & Lifestyle Goods", "Beyond the Basics"),
    (28, "Home & Lifestyle Goods", "Make It Yours"),
    (29, "Home & Lifestyle Goods", "Where Style Lives"),
    (30, "Home & Lifestyle Goods", "Everyday Upgrade"),
    (31, "Home & Lifestyle Goods", "Comfort You Deserve"),
    (32, "Home & Lifestyle Goods", "Inspired Living"),
    (33, "Home & Lifestyle Goods", "Built for Better Homes"),
    (34, "Home & Lifestyle Goods", "A Touch of Tomorrow"),
    (35, "Home & Lifestyle Goods", "Small Things, Big Comfort"),
    (36, "Home & Lifestyle Goods", "More Than a Home"),
    (37, "Home & Lifestyle Goods", "Design Without Compromise"),
    (38, "Home & Lifestyle Goods", "Lifestyle Elevated"),
    (39, "Home & Lifestyle Goods", "Spaces That Shine"),
    (40, "Home & Lifestyle Goods", "Home Sweet Better"),
    (41, "Personal Care & Wellness", "Glow Naturally"),
    (42, "Personal Care & Wellness", "Beauty in Balance"),
    (43, "Personal Care & Wellness", "Care Without Compromise"),
    (44, "Personal Care & Wellness", "Pure Confidence"),
    (45, "Personal Care & Wellness", "Everyday Radiance"),
    (46, "Personal Care & Wellness", "Self-Care, Simplified"),
    (47, "Personal Care & Wellness", "The Power of Pure"),
    (48, "Personal Care & Wellness", "Wellness That Works"),
    (49, "Personal Care & Wellness", "Bold & Beautiful"),
    (50, "Personal Care & Wellness", "Glow Your Way"),
    (51, "Personal Care & Wellness", "Gentle Strength"),
    (52, "Personal Care & Wellness", "Refresh. Renew. Revive."),
    (53, "Personal Care & Wellness", "Clean You Can Trust"),
    (54, "Personal Care & Wellness", "Confidence in Every Drop"),
    (55, "Personal Care & Wellness", "Natural Is the New You"),
    (56, "Personal Care & Wellness", "Better Care, Better You"),
    (57, "Personal Care & Wellness", "Love the Skin You’re In"),
    (58, "Personal Care & Wellness", "Shine Starts Here"),
    (59, "Personal Care & Wellness", "Calm in Every Touch"),
    (60, "Personal Care & Wellness", "Pure Peace of Mind"),
    (61, "Fashion & Apparel", "Wear Your Story"),
    (62, "Fashion & Apparel", "Everyday Icons"),
    (63, "Fashion & Apparel", "Style That Moves"),
    (64, "Fashion & Apparel", "The Future of Fit"),
    (65, "Fashion & Apparel", "Timelessly Bold"),
    (66, "Fashion & Apparel", "Designed for You"),
    (67, "Fashion & Apparel", "Beyond the Trend"),
    (68, "Fashion & Apparel", "Comfort in Motion"),
    (69, "Fashion & Apparel", "Your Everyday Edge"),
    (70, "Fashion & Apparel", "Confidence in Color"),
    (71, "Fashion & Apparel", "Made for Movement"),
    (72, "Fashion & Apparel", "Fit for the Future"),
    (73, "Fashion & Apparel", "Fashion in Flow"),
    (74, "Fashion & Apparel", "The Style Standard"),
    (75, "Fashion & Apparel", "Bold Looks, Everyday Life"),
    (76, "Fashion & Apparel", "Walk the Change"),
    (77, "Fashion & Apparel", "Wear It Well"),
    (78, "Fashion & Apparel", "Built for Bold Living"),
    (79, "Fashion & Apparel", "Everyday Originals"),
    (80, "Fashion & Apparel", "From Runway to Real Life"),
    (81, "Eco-Friendly Consumer Goods", "Green by Nature"),
    (82, "Eco-Friendly Consumer Goods", "Future in Every Choice"),
    (83, "Eco-Friendly Consumer Goods", "Small Footprint, Big Difference"),
    (84, "Eco-Friendly Consumer Goods", "Eco Made Easy"),
    (85, "Eco-Friendly Consumer Goods", "Good for You, Good for Earth"),
    (86, "Eco-Friendly Consumer Goods", "Planet-Friendly Promise"),
    (87, "Eco-Friendly Consumer Goods", "Reuse the Future"),
    (88, "Eco-Friendly Consumer Goods", "Naturally Better"),
    (89, "Eco-Friendly Consumer Goods", "Better Earth, Better Us"),
    (90, "Eco-Friendly Consumer Goods", "Sustainable Everyday"),
    (91, "Eco-Friendly Consumer Goods", "Care That Cares Back"),
    (92, "Eco-Friendly Consumer Goods", "Simple. Sustainable. Strong."),
    (93, "Eco-Friendly Consumer Goods", "Choices That Count"),
    (94, "Eco-Friendly Consumer Goods", "Eco Evolution"),
    (95, "Eco-Friendly Consumer Goods", "The Green Standard"),
    (96, "Eco-Friendly Consumer Goods", "Tomorrow in Your Hands"),
    (97, "Eco-Friendly Consumer Goods", "Rooted in Responsibility"),
    (98, "Eco-Friendly Consumer Goods", "Cleaner Choices, Brighter Future"),
    (99, "Eco-Friendly Consumer Goods", "Pure Planet Power"),
    (100, "Eco-Friendly Consumer Goods", "Made for a Greener You"),
    (101, "Food & Beverage", "Taste the Future"),
    (102, "Food & Beverage", "Harvest to Home"),
    (103, "Food & Beverage", "Made Fresh Daily"),
    (104, "Food & Beverage", "Snack the Smart Way"),
    (105, "Food & Beverage", "Better with Every Bite"),
    (106, "Food & Beverage", "From Nature to Nurture"),
    (107, "Food & Beverage", "The Flavor Journey"),
    (108, "Food & Beverage", "Purely Delicious"),
    (109, "Food & Beverage", "Fuel Your Day"),
    (110, "Food & Beverage", "Savor the Difference"),
    (111, "Food & Beverage", "Naturally Nourishing"),
    (112, "Food & Beverage", "Crave What’s Real"),
    (113, "Food & Beverage", "Fresh Ideas. Fresh Taste."),
    (114, "Food & Beverage", "Sip the Possibilities"),
    (115, "Food & Beverage", "Bold Taste, Bright Life"),
    (116, "Food & Beverage", "Flavor Meets Fun"),
    (117, "Food & Beverage", "Pure Ingredients. Pure Joy."),
    (118, "Food & Beverage", "Delight in Every Bite"),
    (119, "Food & Beverage", "Eat Well. Live Well."),
    (120, "Food & Beverage", "A World of Flavor"),
    (121, "Home & Lifestyle Goods", "Comfort Made Simple"),
    (122, "Home & Lifestyle Goods", "Everyday Essentials Reimagined"),
    (123, "Home & Lifestyle Goods", "Design That Fits"),
    (124, "Home & Lifestyle Goods", "Living in Style"),
    (125, "Home & Lifestyle Goods", "Upgrade Your Everyday"),
    (126, "Home & Lifestyle Goods", "Made for Modern Living"),
    (127, "Home & Lifestyle Goods", "Feel at Home"),
    (128, "Home & Lifestyle Goods", "The Joy of Comfort"),
    (129, "Home & Lifestyle Goods", "Function Meets Flair"),
    (130, "Home & Lifestyle Goods", "Better Living, Better You"),
    (131, "Home & Lifestyle Goods", "Crafted with Purpose"),
    (132, "Home & Lifestyle Goods", "Inspired Comfort"),
    (133, "Home & Lifestyle Goods", "The Everyday Collection"),
    (134, "Home & Lifestyle Goods", "Where Function Meets Style"),
    (135, "Home & Lifestyle Goods", "Design the Everyday"),
    (136, "Home & Lifestyle Goods", "Home for All Seasons"),
    (137, "Home & Lifestyle Goods", "Essentials Made Elegant"),
    (138, "Home & Lifestyle Goods", "Simplify Your Space"),
    (139, "Home & Lifestyle Goods", "Living Perfected"),
    (140, "Home & Lifestyle Goods", "Life at Its Best"),
    (141, "Personal Care & Wellness", "Glow with Confidence"),
    (142, "Personal Care & Wellness", "Feel Fresh, Feel Free"),
    (143, "Personal Care & Wellness", "Nature’s Touch"),
    (144, "Personal Care & Wellness", "Care That Lasts"),
    (145, "Personal Care & Wellness", "Confidence in Care"),
    (146, "Personal Care & Wellness", "Beauty in Motion"),
    (147, "Personal Care & Wellness", "Clean Living"),
    (148, "Personal Care & Wellness", "Naturally Confident"),
    (149, "Personal Care & Wellness", "Wellness Redefined"),
    (150, "Personal Care & Wellness", "Care Every Day"),
    (151, "Personal Care & Wellness", "True to You"),
    (152, "Personal Care & Wellness", "Radiance Revealed"),
    (153, "Personal Care & Wellness", "Feel the Renewal"),
    (154, "Personal Care & Wellness", "Fresh from Nature"),
    (155, "Personal Care & Wellness", "Confidence You Can Feel"),
    (156, "Personal Care & Wellness", "Care That Cares Back"),
    (157, "Personal Care & Wellness", "Live in Balance"),
    (158, "Personal Care & Wellness", "Beauty Beyond Basics"),
    (159, "Personal Care & Wellness", "Refresh Your Routine"),
    (160, "Personal Care & Wellness", "Your Best Glow"),
    (161, "Fashion & Apparel", "Style Without Limits"),
    (162, "Fashion & Apparel", "Everyday Wear. Elevated."),
    (163, "Fashion & Apparel", "Step Into Confidence"),
    (164, "Fashion & Apparel", "Designed for Now"),
    (165, "Fashion & Apparel", "Fit for You"),
    (166, "Fashion & Apparel", "Modern Classics"),
    (167, "Fashion & Apparel", "Your Style, Your Story"),
    (168, "Fashion & Apparel", "Move in Style"),
    (169, "Fashion & Apparel", "Everyday Fit"),
    (170, "Fashion & Apparel", "Redefine Your Look"),
    (171, "Fashion & Apparel", "Effortless Everyday"),
    (172, "Fashion & Apparel", "Wear the Moment"),
    (173, "Fashion & Apparel", "Fashion Made for Life"),
    (174, "Fashion & Apparel", "From Classic to Bold"),
    (175, "Fashion & Apparel", "Style in Motion"),
    (176, "Fashion & Apparel", "Own the Everyday"),
    (177, "Fashion & Apparel", "Built for Style"),
    (178, "Fashion & Apparel", "Life in Style"),
    (179, "Fashion & Apparel", "Fresh Fits Daily"),
    (180, "Fashion & Apparel", "Always On Trend"),
    (181, "Eco-Friendly Consumer Goods", "Earth-Friendly Everyday"),
    (182, "Eco-Friendly Consumer Goods", "Sustainably Yours"),
    (183, "Eco-Friendly Consumer Goods", "The Green Choice"),
    (184, "Eco-Friendly Consumer Goods", "Better Living, Greener Future"),
    (185, "Eco-Friendly Consumer Goods", "Eco Everyday"),
    (186, "Eco-Friendly Consumer Goods", "Planet First"),
    (187, "Eco-Friendly Consumer Goods", "Nature Knows Best"),
    (188, "Eco-Friendly Consumer Goods", "Conscious Choices"),
    (189, "Eco-Friendly Consumer Goods", "For a Cleaner Tomorrow"),
    (190, "Eco-Friendly Consumer Goods", "Future in Focus"),
    (191, "Eco-Friendly Consumer Goods", "Living Green"),
    (192, "Eco-Friendly Consumer Goods", "Planet Positive"),
    (193, "Eco-Friendly Consumer Goods", "Change Starts Small"),
    (194, "Eco-Friendly Consumer Goods", "Good for Earth, Great for You"),
    (195, "Eco-Friendly Consumer Goods", "Smart. Simple. Sustainable."),
    (196, "Eco-Friendly Consumer Goods", "Care for Tomorrow"),
    (197, "Eco-Friendly Consumer Goods", "Eco for Everyone"),
    (198, "Eco-Friendly Consumer Goods", "Cleaner Living"),
    (199, "Eco-Friendly Consumer Goods", "Naturally Simple"),
    (200, "Eco-Friendly Consumer Goods", "Greener Choices, Brighter Days"),
    (201, "Food & Beverage", "Simply Satisfying"),
    (202, "Food & Beverage", "The Taste Standard"),
    (203, "Food & Beverage", "Every Bite Counts"),
    (204, "Food & Beverage", "Naturally Bold"),
    (205, "Food & Beverage", "Pure Flavor Promise"),
    (206, "Food & Beverage", "Snack Smarter, Live Better"),
    (207, "Food & Beverage", "Fresh and Fearless"),
    (208, "Food & Beverage", "Wholesome Every Day"),
    (209, "Food & Beverage", "Taste That Travels"),
    (210, "Food & Beverage", "The Future of Fresh"),
    (211, "Food & Beverage", "Flavor You Can Feel"),
    (212, "Food & Beverage", "Made for Sharing"),
    (213, "Food & Beverage", "Delicious Starts Here"),
    (214, "Food & Beverage", "The Joy of Freshness"),
    (215, "Food & Beverage", "Naturally Flavorful"),
    (216, "Food & Beverage", "Made for Moments"),
    (217, "Food & Beverage", "Purely Yours"),
    (218, "Food & Beverage", "Fuel the Fun"),
    (219, "Food & Beverage", "Savor Something New"),
    (220, "Food & Beverage", "Fresh Thinking, Fresh Eating"),
    (221, "Home & Lifestyle Goods", "Designed for Comfort"),
    (222, "Home & Lifestyle Goods", "Everyday Living Essentials"),
    (223, "Home & Lifestyle Goods", "Style at Home"),
    (224, "Home & Lifestyle Goods", "Better by Design"),
    (225, "Home & Lifestyle Goods", "Home in Harmony"),
    (226, "Home & Lifestyle Goods", "Life Well Furnished"),
    (227, "Home & Lifestyle Goods", "Where Comfort Begins"),
    (228, "Home & Lifestyle Goods", "Every Detail Matters"),
    (229, "Home & Lifestyle Goods", "Crafted to Last"),
    (230, "Home & Lifestyle Goods", "Make Life Cozy"),
    (231, "Home & Lifestyle Goods", "Perfect Fit for Home"),
    (232, "Home & Lifestyle Goods", "Everyday Luxe Living"),
    (233, "Home & Lifestyle Goods", "More Than a Room"),
    (234, "Home & Lifestyle Goods", "Spaces Simplified"),
    (235, "Home & Lifestyle Goods", "Form Meets Function"),
    (236, "Home & Lifestyle Goods", "Your Style Sanctuary"),
    (237, "Home & Lifestyle Goods", "Inspired Interiors"),
    (238, "Home & Lifestyle Goods", "Living, Perfected"),
    (239, "Home & Lifestyle Goods", "Smart Living Solutions"),
    (240, "Home & Lifestyle Goods", "Comfort in Motion"),
    (241, "Personal Care & Wellness", "Naturally You"),
    (242, "Personal Care & Wellness", "Fresh Confidence Daily"),
    (243, "Personal Care & Wellness", "Gentle by Nature"),
    (244, "Personal Care & Wellness", "Pure Care Promise"),
    (245, "Personal Care & Wellness", "Glow Every Day"),
    (246, "Personal Care & Wellness", "Your Daily Balance"),
    (247, "Personal Care & Wellness", "Care That Shines"),
    (248, "Personal Care & Wellness", "Beauty That Lasts"),
    (249, "Personal Care & Wellness", "Refresh the Everyday"),
    (250, "Personal Care & Wellness", "Pure and Simple"),
    (251, "Personal Care & Wellness", "Confidence in Motion"),
    (252, "Personal Care & Wellness", "Naturally Nurtured"),
    (253, "Personal Care & Wellness", "Wellness at Heart"),
    (254, "Personal Care & Wellness", "Every Drop Matters"),
    (255, "Personal Care & Wellness", "Care Made Easy"),
    (256, "Personal Care & Wellness", "The Wellness Standard"),
    (257, "Personal Care & Wellness", "True Beauty, True You"),
    (258, "Personal Care & Wellness", "Pure Comfort Care"),
    (259, "Personal Care & Wellness", "Everyday Glow Up"),
    (260, "Personal Care & Wellness", "Balance in Every Step"),
    (261, "Fashion & Apparel", "Style for Living"),
    (262, "Fashion & Apparel", "Everyday Originals Reimagined"),
    (263, "Fashion & Apparel", "Wear What Moves You"),
    (264, "Fashion & Apparel", "Modern by Nature"),
    (265, "Fashion & Apparel", "Style Simplified"),
    (266, "Fashion & Apparel", "Fit for Today"),
    (267, "Fashion & Apparel", "Style That Works"),
    (268, "Fashion & Apparel", "Everyday Confidence"),
    (269, "Fashion & Apparel", "Move Boldly"),
    (270, "Fashion & Apparel", "Wear the Change"),
    (271, "Fashion & Apparel", "Effortless Fit"),
    (272, "Fashion & Apparel", "Live in Style Daily"),
    (273, "Fashion & Apparel", "The Everyday Look"),
    (274, "Fashion & Apparel", "Fashion Without Limits"),
    (275, "Fashion & Apparel", "Trend Meets Comfort"),
    (276, "Fashion & Apparel", "Bold Looks, Bright Living"),
    (277, "Fashion & Apparel", "Wear It Proud"),
    (278, "Fashion & Apparel", "Every Fit Matters"),
    (279, "Fashion & Apparel", "Designed for Movement"),
    (280, "Fashion & Apparel", "Style That Stays"),
    (281, "Eco-Friendly Consumer Goods", "Made Green. Made Great."),
    (282, "Eco-Friendly Consumer Goods", "Sustainable Starts Here"),
    (283, "Eco-Friendly Consumer Goods", "Everyday Earth Care"),
    (284, "Eco-Friendly Consumer Goods", "Eco-Friendly Made Simple"),
    (285, "Eco-Friendly Consumer Goods", "The Future We Choose"),
    (286, "Eco-Friendly Consumer Goods", "Planet in Balance"),
    (287, "Eco-Friendly Consumer Goods", "Better World, Better Life"),
    (288, "Eco-Friendly Consumer Goods", "Green Living Today"),
    (289, "Eco-Friendly Consumer Goods", "Good Earth Choices"),
    (290, "Eco-Friendly Consumer Goods", "Future First"),
    (291, "Eco-Friendly Consumer Goods", "Eco Smart Living"),
    (292, "Eco-Friendly Consumer Goods", "Green by Design"),
    (293, "Eco-Friendly Consumer Goods", "Cleaner Planet Promise"),
    (294, "Eco-Friendly Consumer Goods", "Eco in Action"),
    (295, "Eco-Friendly Consumer Goods", "The Responsible Choice"),
    (296, "Eco-Friendly Consumer Goods", "Tomorrow’s Earth Today"),
    (297, "Eco-Friendly Consumer Goods", "Better Choices, Brighter Future"),
    (298, "Eco-Friendly Consumer Goods", "Planet-Friendly Living"),
    (299, "Eco-Friendly Consumer Goods", "Naturally Good, Naturally Green"),
    (300, "Eco-Friendly Consumer Goods", "Eco Living for All"),
    (301, "Food & Beverage", "Goodness in Every Bite"),
    (302, "Food & Beverage", "Naturally Fresh, Naturally You"),
    (303, "Food & Beverage", "Snack with Purpose"),
    (304, "Food & Beverage", "The Flavor Fix"),
    (305, "Food & Beverage", "Wholesome. Wonderful."),
    (306, "Food & Beverage", "Fresh from the Source"),
    (307, "Food & Beverage", "Taste That Inspires"),
    (308, "Food & Beverage", "The Everyday Treat"),
    (309, "Food & Beverage", "Farm Fresh Flavor"),
    (310, "Food & Beverage", "Happiness in a Bite"),
    (311, "Food & Beverage", "Better Flavor Forward"),
    (312, "Food & Beverage", "Naturally Satisfying"),
    (313, "Food & Beverage", "A Taste You Trust"),
    (314, "Food & Beverage", "Eat Pure. Live Pure."),
    (315, "Food & Beverage", "Crafted with Goodness"),
    (316, "Food & Beverage", "Snack Time, Anytime"),
    (317, "Food & Beverage", "The Joy of Simple Food"),
    (318, "Food & Beverage", "Fresh Flavor Found"),
    (319, "Food & Beverage", "Real Taste. Real Life."),
    (320, "Food & Beverage", "Made to Nourish"),
    (321, "Home & Lifestyle Goods", "Everyday Home Harmony"),
    (322, "Home & Lifestyle Goods", "Comfort Crafted Daily"),
    (323, "Home & Lifestyle Goods", "Design That Delivers"),
    (324, "Home & Lifestyle Goods", "Home with Heart"),
    (325, "Home & Lifestyle Goods", "Better Living Every Day"),
    (326, "Home & Lifestyle Goods", "Your Space, Your Story"),
    (327, "Home & Lifestyle Goods", "Crafting Cozy Moments"),
    (328, "Home & Lifestyle Goods", "Inspired Home Living"),
    (329, "Home & Lifestyle Goods", "Comfort in Style"),
    (330, "Home & Lifestyle Goods", "Everyday Home Solutions"),
    (331, "Home & Lifestyle Goods", "Designed Around You"),
    (332, "Home & Lifestyle Goods", "Living in Balance"),
    (333, "Home & Lifestyle Goods", "Function You Feel"),
    (334, "Home & Lifestyle Goods", "Practical Meets Beautiful"),
    (335, "Home & Lifestyle Goods", "Comfort That Lasts"),
    (336, "Home & Lifestyle Goods", "Better Spaces, Brighter Days"),
    (337, "Home & Lifestyle Goods", "Where Comfort Grows"),
    (338, "Home & Lifestyle Goods", "Everyday Ease"),
    (339, "Home & Lifestyle Goods", "Style for Living Well"),
    (340, "Home & Lifestyle Goods", "Home Comfort Revolution"),
    (341, "Personal Care & Wellness", "Naturally Radiant"),
    (342, "Personal Care & Wellness", "Care You Can Feel"),
    (343, "Personal Care & Wellness", "Gentle Power"),
    (344, "Personal Care & Wellness", "Glow Made Simple"),
    (345, "Personal Care & Wellness", "Confidence Every Morning"),
    (346, "Personal Care & Wellness", "Pure Renewal"),
    (347, "Personal Care & Wellness", "Daily Care, Daily Glow"),
    (348, "Personal Care & Wellness", "Love Your Routine"),
    (349, "Personal Care & Wellness", "Clean Confidence"),
    (350, "Personal Care & Wellness", "Fresh Looks Good"),
    (351, "Personal Care & Wellness", "Healthy Skin, Happy You"),
    (352, "Personal Care & Wellness", "Feel Fresh, Feel Strong"),
    (353, "Personal Care & Wellness", "The Beauty Standard"),
    (354, "Personal Care & Wellness", "Glow the Natural Way"),
    (355, "Personal Care & Wellness", "Confidence Made Pure"),
    (356, "Personal Care & Wellness", "Refresh Every Day"),
    (357, "Personal Care & Wellness", "Pure Glow Promise"),
    (358, "Personal Care & Wellness", "Every Step in Balance"),
    (359, "Personal Care & Wellness", "Care Beyond Clean"),
    (360, "Personal Care & Wellness", "Glow Inside and Out"),
    (361, "Fashion & Apparel", "Everyday Looks, Endless Style"),
    (362, "Fashion & Apparel", "Wear the Future"),
    (363, "Fashion & Apparel", "Confidence in Every Step"),
    (364, "Fashion & Apparel", "Style for All Seasons"),
    (365, "Fashion & Apparel", "Everyday Wear, Everyday Flair"),
    (366, "Fashion & Apparel", "Bold by Nature"),
    (367, "Fashion & Apparel", "Fashion Your Way"),
    (368, "Fashion & Apparel", "The Fit You Want"),
    (369, "Fashion & Apparel", "Always in Motion"),
    (370, "Fashion & Apparel", "Style Simplified Daily"),
    (371, "Fashion & Apparel", "Wear What Matters"),
    (372, "Fashion & Apparel", "Designed for Bold Moves"),
    (373, "Fashion & Apparel", "The Everyday Outfit"),
    (374, "Fashion & Apparel", "Fit That Lasts"),
    (375, "Fashion & Apparel", "Style Without Effort"),
    (376, "Fashion & Apparel", "Bold Looks, Bright Confidence"),
    (377, "Fashion & Apparel", "Made for the Moment"),
    (378, "Fashion & Apparel", "Wear the Day Well"),
    (379, "Fashion & Apparel", "Confidence in Color and Fit"),
    (380, "Fashion & Apparel", "Style That Lives On"),
    (381, "Eco-Friendly Consumer Goods", "Green Living Simplified"),
    (382, "Eco-Friendly Consumer Goods", "Sustainability Made Easy"),
    (383, "Eco-Friendly Consumer Goods", "Planet Smart Choices"),
    (384, "Eco-Friendly Consumer Goods", "Eco Every Moment"),
    (385, "Eco-Friendly Consumer Goods", "Future in Balance"),
    (386, "Eco-Friendly Consumer Goods", "Earth Matters Every Day"),
    (387, "Eco-Friendly Consumer Goods", "Naturally Sustainable"),
    (388, "Eco-Friendly Consumer Goods", "Eco for Life"),
    (389, "Eco-Friendly Consumer Goods", "Cleaner Earth, Cleaner Life"),
    (390, "Eco-Friendly Consumer Goods", "Planet First Promise"),
    (391, "Eco-Friendly Consumer Goods", "Living Lightly"),
    (392, "Eco-Friendly Consumer Goods", "Small Steps, Big Change"),
    (393, "Eco-Friendly Consumer Goods", "Green Living, Simple Living"),
    (394, "Eco-Friendly Consumer Goods", "Tomorrow Starts Today"),
    (395, "Eco-Friendly Consumer Goods", "Sustainable Style"),
    (396, "Eco-Friendly Consumer Goods", "Eco Living Made Better"),
    (397, "Eco-Friendly Consumer Goods", "Planet-Friendly Promise"),
    (398, "Eco-Friendly Consumer Goods", "Better Earth, Better Everyday"),
    (399, "Eco-Friendly Consumer Goods", "Nature’s Everyday Choice"),
    (400, "Eco-Friendly Consumer Goods", "Living the Green Way"),
    (401, "Software & Apps", "Code Your Future"),
    (402, "Software & Apps", "Apps Without Limits"),
    (403, "Software & Apps", "Digital Made Simple"),
    (404, "Software & Apps", "Click. Create. Conquer."),
    (405, "Software & Apps", "Experience the Upgrade"),
    (406, "Software & Apps", "Connected by Design"),
    (407, "Software & Apps", "Solutions at Speed"),
    (408, "Software & Apps", "Your Workflow, Reinvented"),
    (409, "Software & Apps", "Everyday Efficiency"),
    (410, "Software & Apps", "The Future in Your Hands"),
    (411, "Software & Apps", "Smart Tools, Smart Life"),
    (412, "Software & Apps", "Where Ideas Flow"),
    (413, "Software & Apps", "Innovation at Your Fingertips"),
    (414, "Software & Apps", "Streamlined for Success"),
    (415, "Software & Apps", "Your World, Upgraded"),
    (416, "Software & Apps", "Tech That Works for You"),
    (417, "Software & Apps", "Power in Every Click"),
    (418, "Software & Apps", "Transform How You Work"),
    (419, "Software & Apps", "Efficiency Unleashed"),
    (420, "Software & Apps", "Productivity Perfected"),
    (421, "Hardware & Devices", "Engineered for Excellence"),
    (422, "Hardware & Devices", "Performance Without Limits"),
    (423, "Hardware & Devices", "Built for the Future"),
    (424, "Hardware & Devices", "Power. Precision. Performance."),
    (425, "Hardware & Devices", "Your Digital Companion"),
    (426, "Hardware & Devices", "Stronger. Faster. Smarter."),
    (427, "Hardware & Devices", "Tech You Can Trust"),
    (428, "Hardware & Devices", "Innovation in Every Inch"),
    (429, "Hardware & Devices", "Tools of Tomorrow"),
    (430, "Hardware & Devices", "Design Meets Durability"),
    (431, "Hardware & Devices", "Crafted for Power"),
    (432, "Hardware & Devices", "Performance in Motion"),
    (433, "Hardware & Devices", "Made to Endure"),
    (434, "Hardware & Devices", "Precision Engineered"),
    (435, "Hardware & Devices", "Smart Inside and Out"),
    (436, "Hardware & Devices", "Power That Lasts"),
    (437, "Hardware & Devices", "Devices That Deliver"),
    (438, "Hardware & Devices", "Innovation You Can Hold"),
    (439, "Hardware & Devices", "Redefining Performance"),
    (440, "Hardware & Devices", "Hardware Evolved"),
    (441, "Cloud & Data", "Your Cloud, Your Way"),
    (442, "Cloud & Data", "Data That Works for You"),
    (443, "Cloud & Data", "Infinite Storage, Infinite Ideas"),
    (444, "Cloud & Data", "Smarter in the Cloud"),
    (445, "Cloud & Data", "Where Data Meets Design"),
    (446, "Cloud & Data", "Secure. Simple. Scalable."),
    (447, "Cloud & Data", "Cloud Confidence"),
    (448, "Cloud & Data", "Power Beyond Borders"),
    (449, "Cloud & Data", "Data-Driven Decisions"),
    (450, "Cloud & Data", "Cloud Without Limits"),
    (451, "Cloud & Data", "Scale Smarter"),
    (452, "Cloud & Data", "Seamless Data. Seamless Life."),
    (453, "Cloud & Data", "Future-Proof Your Cloud"),
    (454, "Cloud & Data", "Intelligence in Action"),
    (455, "Cloud & Data", "Data Made Simple"),
    (456, "Cloud & Data", "The Cloud Revolution"),
    (457, "Cloud & Data", "Securely Yours"),
    (458, "Cloud & Data", "Cloud That Cares"),
    (459, "Cloud & Data", "Infinite Possibilities"),
    (460, "Cloud & Data", "Smart Data. Smart World."),
    (461, "AI & Innovation", "Powered by Possibility"),
    (462, "AI & Innovation", "Intelligence in Motion"),
    (463, "AI & Innovation", "Smarter Every Day"),
    (464, "AI & Innovation", "Tomorrow’s Tech Today"),
    (465, "AI & Innovation", "Think Smarter"),
    (466, "AI & Innovation", "The AI Advantage"),
    (467, "AI & Innovation", "Learning Made Intelligent"),
    (468, "AI & Innovation", "Ideas That Think"),
    (469, "AI & Innovation", "Innovation Without Boundaries"),
    (470, "AI & Innovation", "Machine Meets Mind"),
    (471, "AI & Innovation", "Future of Thinking"),
    (472, "AI & Innovation", "Smart Is the New Strong"),
    (473, "AI & Innovation", "AI That Empowers"),
    (474, "AI & Innovation", "Intelligence Everywhere"),
    (475, "AI & Innovation", "The Next Evolution"),
    (476, "AI & Innovation", "Driven by Data"),
    (477, "AI & Innovation", "Adaptive by Design"),
    (478, "AI & Innovation", "Smarter Starts Here"),
    (479, "AI & Innovation", "Artificially Brilliant"),
    (480, "AI & Innovation", "Innovate. Integrate. Elevate."),
    (481, "Tech Lifestyle", "Live the Upgrade"),
    (482, "Tech Lifestyle", "Innovation for Everyone"),
    (483, "Tech Lifestyle", "Smart Living Simplified"),
    (484, "Tech Lifestyle", "Life. Powered."),
    (485, "Tech Lifestyle", "Connected Every Day"),
    (486, "Tech Lifestyle", "Tech That Fits Your Life"),
    (487, "Tech Lifestyle", "Your Digital Lifestyle"),
    (488, "Tech Lifestyle", "Living the Smart Way"),
    (489, "Tech Lifestyle", "Simplify with Tech"),
    (490, "Tech Lifestyle", "Tech That Moves You"),
    (491, "Tech Lifestyle", "Everyday Innovation"),
    (492, "Tech Lifestyle", "Smart Choices, Smarter Life"),
    (493, "Tech Lifestyle", "Tech Without Barriers"),
    (494, "Tech Lifestyle", "Living, Upgraded"),
    (495, "Tech Lifestyle", "Smart Is Simple"),
    (496, "Tech Lifestyle", "The Tech Edge"),
    (497, "Tech Lifestyle", "Life in Sync"),
    (498, "Tech Lifestyle", "Powered by Progress"),
    (499, "Tech Lifestyle", "Always Connected"),
    (500, "Tech Lifestyle", "Future in Focus"),
    (501, "Software & Apps", "Seamless Solutions"),
    (502, "Software & Apps", "Everyday Innovation Engine"),
    (503, "Software & Apps", "Smart Tools, Better Work"),
    (504, "Software & Apps", "Apps That Adapt"),
    (505, "Software & Apps", "Your Digital Edge"),
    (506, "Software & Apps", "Next-Level Productivity"),
    (507, "Software & Apps", "Your Workflow Partner"),
    (508, "Software & Apps", "Simplify Your World"),
    (509, "Software & Apps", "The Power of Code"),
    (510, "Software & Apps", "Click to Innovate"),
    (511, "Software & Apps", "Apps for All"),
    (512, "Software & Apps", "Innovation Inside"),
    (513, "Software & Apps", "Your Daily Upgrade"),
    (514, "Software & Apps", "Software that Scales"),
    (515, "Software & Apps", "Connected Workflow"),
    (516, "Software & Apps", "Ideas in Motion"),
    (517, "Software & Apps", "Digital Tools for Real Life"),
    (518, "Software & Apps", "Efficiency Engineered"),
    (519, "Software & Apps", "Apps with Impact"),
    (520, "Software & Apps", "Smart Starts Here"),
    (521, "Hardware & Devices", "The Power of Precision"),
    (522, "Hardware & Devices", "Designed to Perform"),
    (523, "Hardware & Devices", "Tech That Lasts"),
    (524, "Hardware & Devices", "Performance Reimagined"),
    (525, "Hardware & Devices", "Your Everyday Device"),
    (526, "Hardware & Devices", "Hardware You Can Count On"),
    (527, "Hardware & Devices", "Redefining Reliability"),
    (528, "Hardware & Devices", "Performance Perfected"),
    (529, "Hardware & Devices", "Smart Design, Smart Use"),
    (530, "Hardware & Devices", "Engineered for Everyday"),
    (531, "Hardware & Devices", "Power with Purpose"),
    (532, "Hardware & Devices", "Innovation Engineered"),
    (533, "Hardware & Devices", "Built to Outperform"),
    (534, "Hardware & Devices", "Devices That Matter"),
    (535, "Hardware & Devices", "Tech in Motion"),
    (536, "Hardware & Devices", "Endless Power"),
    (537, "Hardware & Devices", "Strong by Design"),
    (538, "Hardware & Devices", "Smart Tools, Real Results"),
    (539, "Hardware & Devices", "Performance at Heart"),
    (540, "Hardware & Devices", "Designed for Impact"),
    (541, "Cloud & Data", "Smart Cloud. Smart Future."),
    (542, "Cloud & Data", "Data That Scales"),
    (543, "Cloud & Data", "Infinite Ideas, Infinite Cloud"),
    (544, "Cloud & Data", "Your Data, Simplified"),
    (545, "Cloud & Data", "Cloud for All"),
    (546, "Cloud & Data", "Secure Cloud Solutions"),
    (547, "Cloud & Data", "Empowered by Data"),
    (548, "Cloud & Data", "Seamless Cloud Living"),
    (549, "Cloud & Data", "Where Data Works"),
    (550, "Cloud & Data", "The Data Difference"),
    (551, "Cloud & Data", "Confidence in the Cloud"),
    (552, "Cloud & Data", "Always Available"),
    (553, "Cloud & Data", "Data in Motion"),
    (554, "Cloud & Data", "Scale Without Limits"),
    (555, "Cloud & Data", "Cloud Confidence, Daily"),
    (556, "Cloud & Data", "Your Secure Future"),
    (557, "Cloud & Data", "Where Data Flows"),
    (558, "Cloud & Data", "Simplify the Cloud"),
    (559, "Cloud & Data", "Cloud in Action"),
    (560, "Cloud & Data", "Infinite Access"),
    (561, "AI & Innovation", "Innovation That Thinks"),
    (562, "AI & Innovation", "AI for All"),
    (563, "AI & Innovation", "Think Forward"),
    (564, "AI & Innovation", "Intelligence Simplified"),
    (565, "AI & Innovation", "Ideas That Learn"),
    (566, "AI & Innovation", "Artificial Advantage"),
    (567, "AI & Innovation", "The Smart Revolution"),
    (568, "AI & Innovation", "Everyday AI"),
    (569, "AI & Innovation", "Learning in Action"),
    (570, "AI & Innovation", "Smarter, Together"),
    (571, "AI & Innovation", "The Future Learns"),
    (572, "AI & Innovation", "Tech That Thinks"),
    (573, "AI & Innovation", "Data Meets Imagination"),
    (574, "AI & Innovation", "Innovation in Real Time"),
    (575, "AI & Innovation", "Adaptive Intelligence"),
    (576, "AI & Innovation", "Smarter Living"),
    (577, "AI & Innovation", "Brains Behind the Code"),
    (578, "AI & Innovation", "Thinking Made Simple"),
    (579, "AI & Innovation", "AI That Adapts"),
    (580, "AI & Innovation", "Beyond the Algorithm"),
    (581, "Tech Lifestyle", "Life, Simplified by Tech"),
    (582, "Tech Lifestyle", "Everyday Living, Smarter"),
    (583, "Tech Lifestyle", "Tech at Heart"),
    (584, "Tech Lifestyle", "Innovation for Living"),
    (585, "Tech Lifestyle", "Always Ahead"),
    (586, "Tech Lifestyle", "Live in Sync with Tech"),
    (587, "Tech Lifestyle", "Digital Living Made Easy"),
    (588, "Tech Lifestyle", "The Smart Choice"),
    (589, "Tech Lifestyle", "Living Connected"),
    (590, "Tech Lifestyle", "Innovation at Home"),
    (591, "Tech Lifestyle", "Tech for Today"),
    (592, "Tech Lifestyle", "Simpler, Smarter Living"),
    (593, "Tech Lifestyle", "Powered by Progress"),
    (594, "Tech Lifestyle", "Innovation in Motion"),
    (595, "Tech Lifestyle", "Your Tech-Ready Life"),
    (596, "Tech Lifestyle", "Always Evolving"),
    (597, "Tech Lifestyle", "Future in Everyday Life"),
    (598, "Tech Lifestyle", "Smarter Living Starts Here"),
    (599, "Tech Lifestyle", "Everyday Digital Edge"),
    (600, "Tech Lifestyle", "Life Without Limits"),
    (601, "Consulting & Strategy", "Partnering for Progress"),
    (602, "Consulting & Strategy", "Advisors in Action"),
    (603, "Consulting & Strategy", "Future-Proof Solutions"),
    (604, "Consulting & Strategy", "Guided by Insight"),
    (605, "Consulting & Strategy", "Your Strategy, Our Expertise"),
    (606, "Consulting & Strategy", "Navigating Complexity"),
    (607, "Consulting & Strategy", "Turning Vision into Value"),
    (608, "Consulting & Strategy", "Advisory with Impact"),
    (609, "Consulting & Strategy", "Smart Decisions, Strong Growth"),
    (610, "Consulting & Strategy", "Trusted Guidance"),
    (611, "Consulting & Strategy", "Strategies That Scale"),
    (612, "Consulting & Strategy", "Solutions for Tomorrow"),
    (613, "Consulting & Strategy", "Insight in Action"),
    (614, "Consulting & Strategy", "Your Path to Growth"),
    (615, "Consulting & Strategy", "Clarity for Complexity"),
    (616, "Consulting & Strategy", "Enterprise Advisory Edge"),
    (617, "Consulting & Strategy", "Results That Matter"),
    (618, "Consulting & Strategy", "Strategy Simplified"),
    (619, "Consulting & Strategy", "Partnering for Change"),
    (620, "Consulting & Strategy", "Advisors for the Future"),
    (621, "Enterprise Software", "Software That Scales"),
    (622, "Enterprise Software", "Solutions Without Limits"),
    (623, "Enterprise Software", "Your Digital Backbone"),
    (624, "Enterprise Software", "Enterprise Made Easy"),
    (625, "Enterprise Software", "Code for Companies"),
    (626, "Enterprise Software", "Systems That Deliver"),
    (627, "Enterprise Software", "Software. Simplified."),
    (628, "Enterprise Software", "Your Platform Partner"),
    (629, "Enterprise Software", "Business Runs Here"),
    (630, "Enterprise Software", "Performance That Lasts"),
    (631, "Enterprise Software", "Enterprise Ready"),
    (632, "Enterprise Software", "Solutions That Scale"),
    (633, "Enterprise Software", "Your Tech Partner"),
    (634, "Enterprise Software", "Software in Motion"),
    (635, "Enterprise Software", "Innovating Enterprise"),
    (636, "Enterprise Software", "Smart Enterprise Tools"),
    (637, "Enterprise Software", "Code That Connects"),
    (638, "Enterprise Software", "Platforms with Purpose"),
    (639, "Enterprise Software", "Business, Upgraded"),
    (640, "Enterprise Software", "Enterprise Simplified"),
    (641, "Financial & Professional Services", "Trusted by Business"),
    (642, "Financial & Professional Services", "Confidence in Every Transaction"),
    (643, "Financial & Professional Services", "Your Growth Partner"),
    (644, "Financial & Professional Services", "Advisory You Can Count On"),
    (645, "Financial & Professional Services", "Finance That Moves You"),
    (646, "Financial & Professional Services", "Smart Capital. Smart Growth."),
    (647, "Financial & Professional Services", "Your Finance Partner"),
    (648, "Financial & Professional Services", "Investing in Innovation"),
    (649, "Financial & Professional Services", "Professional. Reliable. Ready."),
    (650, "Financial & Professional Services", "Where Finance Meets Future"),
    (651, "Financial & Professional Services", "Strong Capital, Strong Growth"),
    (652, "Financial & Professional Services", "Your Trusted Advisor"),
    (653, "Financial & Professional Services", "Secure. Strategic. Smart."),
    (654, "Financial & Professional Services", "Finance Without Boundaries"),
    (655, "Financial & Professional Services", "Partners in Performance"),
    (656, "Financial & Professional Services", "Your Capital Advantage"),
    (657, "Financial & Professional Services", "Advisory with Confidence"),
    (658, "Financial & Professional Services", "Built on Trust"),
    (659, "Financial & Professional Services", "Your Business. Our Focus."),
    (660, "Financial & Professional Services", "Professional Services Simplified"),
    (661, "Logistics & Operations", "Supply Chain Simplified"),
    (662, "Logistics & Operations", "Delivering What Matters"),
    (663, "Logistics & Operations", "Operations Optimized"),
    (664, "Logistics & Operations", "The Logistics Edge"),
    (665, "Logistics & Operations", "Your Supply Partner"),
    (666, "Logistics & Operations", "Seamless Supply Chains"),
    (667, "Logistics & Operations", "Global Reach, Local Impact"),
    (668, "Logistics & Operations", "Where Efficiency Meets Scale"),
    (669, "Logistics & Operations", "Built for Business"),
    (670, "Logistics & Operations", "Smart Operations"),
    (671, "Logistics & Operations", "Moving Business Forward"),
    (672, "Logistics & Operations", "Delivering Confidence"),
    (673, "Logistics & Operations", "Supply Chain Confidence"),
    (674, "Logistics & Operations", "Enterprise Logistics Partner"),
    (675, "Logistics & Operations", "Efficiency in Motion"),
    (676, "Logistics & Operations", "Your Operations Advantage"),
    (677, "Logistics & Operations", "Logistics Made Easy"),
    (678, "Logistics & Operations", "The Power of Precision Delivery"),
    (679, "Logistics & Operations", "Scale. Ship. Succeed."),
    (680, "Logistics & Operations", "Smart Logistics Solutions"),
    (681, "Enterprise Cloud & Security", "Secure the Future"),
    (682, "Enterprise Cloud & Security", "Cloud Confidence for Business"),
    (683, "Enterprise Cloud & Security", "Your Data, Our Defense"),
    (684, "Enterprise Cloud & Security", "Enterprise Security Simplified"),
    (685, "Enterprise Cloud & Security", "Safeguarding Success"),
    (686, "Enterprise Cloud & Security", "Cloud Security That Scales"),
    (687, "Enterprise Cloud & Security", "Future-Proof Security"),
    (688, "Enterprise Cloud & Security", "Business Beyond Borders"),
    (689, "Enterprise Cloud & Security", "Secure. Strong. Scalable."),
    (690, "Enterprise Cloud & Security", "The Cloud for Business"),
    (691, "Enterprise Cloud & Security", "Enterprise Security Edge"),
    (692, "Enterprise Cloud & Security", "Cloud That Protects"),
    (693, "Enterprise Cloud & Security", "Your Security Partner"),
    (694, "Enterprise Cloud & Security", "Safe. Smart. Secure."),
    (695, "Enterprise Cloud & Security", "Cloud Power, Cloud Protection"),
    (696, "Enterprise Cloud & Security", "Your Data. Defended."),
    (697, "Enterprise Cloud & Security", "Enterprise Defense Solutions"),
    (698, "Enterprise Cloud & Security", "Protection in Progress"),
    (699, "Enterprise Cloud & Security", "Cloud Beyond Limits"),
    (700, "Enterprise Cloud & Security", "Enterprise Cloud Confidence"),
    (701, "Consulting & Strategy", "Advisory that Delivers"),
    (702, "Consulting & Strategy", "Your Growth Partner"),
    (703, "Consulting & Strategy", "Enterprise Expertise"),
    (704, "Consulting & Strategy", "Trusted Insights"),
    (705, "Consulting & Strategy", "Strategic Solutions Simplified"),
    (706, "Consulting & Strategy", "Future-Ready Strategy"),
    (707, "Consulting & Strategy", "Smart Growth Guidance"),
    (708, "Consulting & Strategy", "Insight. Action. Results."),
    (709, "Consulting & Strategy", "Scaling with Strategy"),
    (710, "Consulting & Strategy", "Clarity Creates Growth"),
    (711, "Consulting & Strategy", "Performance Partnered"),
    (712, "Consulting & Strategy", "Guiding Transformation"),
    (713, "Consulting & Strategy", "Strategy That Works"),
    (714, "Consulting & Strategy", "Innovation in Advisory"),
    (715, "Consulting & Strategy", "Your Change Navigator"),
    (716, "Consulting & Strategy", "Enterprise Edge"),
    (717, "Consulting & Strategy", "Results-Driven Strategy"),
    (718, "Consulting & Strategy", "Advisors for Growth"),
    (719, "Consulting & Strategy", "Simplifying Enterprise Growth"),
    (720, "Consulting & Strategy", "Your Strategy Simplified"),
    (721, "Enterprise Software", "Smart Systems for Business"),
    (722, "Enterprise Software", "Software for Scale"),
    (723, "Enterprise Software", "Enterprise-Ready Solutions"),
    (724, "Enterprise Software", "Your Platform Advantage"),
    (725, "Enterprise Software", "Business Beyond Boundaries"),
    (726, "Enterprise Software", "Software with Strength"),
    (727, "Enterprise Software", "Enterprise Integration Made Easy"),
    (728, "Enterprise Software", "Smart Software Edge"),
    (729, "Enterprise Software", "Business Tools That Work"),
    (730, "Enterprise Software", "Scaling with Software"),
    (731, "Enterprise Software", "Enterprise Simplified"),
    (732, "Enterprise Software", "Code Meets Enterprise"),
    (733, "Enterprise Software", "Smart Systems, Smart Scale"),
    (734, "Enterprise Software", "Your Enterprise Partner"),
    (735, "Enterprise Software", "Enterprise Tech. Everyday."),
    (736, "Enterprise Software", "Solutions That Last"),
    (737, "Enterprise Software", "Your Business Platform"),
    (738, "Enterprise Software", "Software. Secured."),
    (739, "Enterprise Software", "Simplifying Scale"),
    (740, "Enterprise Software", "Code for Growth"),
    (741, "Financial & Professional Services", "Advisory for Enterprise"),
    (742, "Financial & Professional Services", "Finance That Works"),
    (743, "Financial & Professional Services", "Strategic Finance Partner"),
    (744, "Financial & Professional Services", "Growth Backed by Capital"),
    (745, "Financial & Professional Services", "Your Professional Partner"),
    (746, "Financial & Professional Services", "Enterprise-Grade Confidence"),
    (747, "Financial & Professional Services", "Finance That Scales"),
    (748, "Financial & Professional Services", "Smart Financial Services"),
    (749, "Financial & Professional Services", "Trust in Every Number"),
    (750, "Financial & Professional Services", "Professional Confidence"),
    (751, "Financial & Professional Services", "Enterprise Finance Edge"),
    (752, "Financial & Professional Services", "Partners in Growth"),
    (753, "Financial & Professional Services", "Capital with Confidence"),
    (754, "Financial & Professional Services", "Advisory Beyond Boundaries"),
    (755, "Financial & Professional Services", "Strong Finance, Strong Business"),
    (756, "Financial & Professional Services", "Enterprise Ready Advisory"),
    (757, "Financial & Professional Services", "Smart Solutions. Strong Finance."),
    (758, "Financial & Professional Services", "Finance Simplified for Enterprise"),
    (759, "Financial & Professional Services", "Professional Power"),
    (760, "Financial & Professional Services", "Confidence That Counts"),
    (761, "Logistics & Operations", "Enterprise Logistics Edge"),
    (762, "Logistics & Operations", "Efficient by Design"),
    (763, "Logistics & Operations", "Supply Chain Strength"),
    (764, "Logistics & Operations", "Global. Local. Seamless."),
    (765, "Logistics & Operations", "Logistics Without Limits"),
    (766, "Logistics & Operations", "Scaling Supply Chains"),
    (767, "Logistics & Operations", "Smart Logistics Edge"),
    (768, "Logistics & Operations", "Global Reach. Local Care."),
    (769, "Logistics & Operations", "Enterprise-Grade Operations"),
    (770, "Logistics & Operations", "Logistics with Impact"),
    (771, "Logistics & Operations", "Smart Delivery Systems"),
    (772, "Logistics & Operations", "Efficiency That Scales"),
    (773, "Logistics & Operations", "Logistics Reinvented"),
    (774, "Logistics & Operations", "Operations Simplified"),
    (775, "Logistics & Operations", "Your Enterprise Delivery Partner"),
    (776, "Logistics & Operations", "Supply Chain Evolution"),
    (777, "Logistics & Operations", "Logistics That Perform"),
    (778, "Logistics & Operations", "From Planning to Delivery"),
    (779, "Logistics & Operations", "Scale with Confidence"),
    (780, "Logistics & Operations", "Enterprise-First Logistics"),
    (781, "Enterprise Cloud & Security", "Cloud That Protects"),
    (782, "Enterprise Cloud & Security", "Enterprise Data, Secured"),
    (783, "Enterprise Cloud & Security", "Your Trusted Cloud Partner"),
    (784, "Enterprise Cloud & Security", "Enterprise Cloud Edge"),
    (785, "Enterprise Cloud & Security", "Smart Security for Scale"),
    (786, "Enterprise Cloud & Security", "Cloud Without Borders"),
    (787, "Enterprise Cloud & Security", "Your Secure Business Future"),
    (788, "Enterprise Cloud & Security", "Enterprise in the Cloud"),
    (789, "Enterprise Cloud & Security", "Cloud That Delivers"),
    (790, "Enterprise Cloud & Security", "Safe. Simple. Secure."),
    (791, "Enterprise Cloud & Security", "Enterprise Security Advantage"),
    (792, "Enterprise Cloud & Security", "Protect What Matters"),
    (793, "Enterprise Cloud & Security", "Business Secured"),
    (794, "Enterprise Cloud & Security", "Cloud Made Enterprise-Ready"),
    (795, "Enterprise Cloud & Security", "Your Defense Partner"),
    (796, "Enterprise Cloud & Security", "Enterprise Security Simplified"),
    (797, "Enterprise Cloud & Security", "Stronger Cloud. Stronger Business."),
    (798, "Enterprise Cloud & Security", "Cloud Solutions That Scale"),
    (799, "Enterprise Cloud & Security", "Securing Success"),
    (800, "Enterprise Cloud & Security", "Enterprise Cloud Without Limits"),
    (801, "Consulting & Strategy", "Smart Guidance for Growth"),
    (802, "Consulting & Strategy", "Your Change Partner"),
    (803, "Consulting & Strategy", "Enterprise Growth Engine"),
    (804, "Consulting & Strategy", "Advisory for Tomorrow"),
    (805, "Consulting & Strategy", "Solutions That Scale Up"),
    (806, "Consulting & Strategy", "Transformation Simplified"),
    (807, "Consulting & Strategy", "Enterprise Advisory Edge"),
    (808, "Consulting & Strategy", "Results-First Strategy"),
    (809, "Consulting & Strategy", "Partners in Progress"),
    (810, "Consulting & Strategy", "Strategy Made Simple"),
    (811, "Consulting & Strategy", "Growth Advisory Edge"),
    (812, "Consulting & Strategy", "Your Pathway to Scale"),
    (813, "Consulting & Strategy", "Smart Advisory Services"),
    (814, "Consulting & Strategy", "Strategy that Performs"),
    (815, "Consulting & Strategy", "Change with Confidence"),
    (816, "Consulting & Strategy", "Enterprise Insight Partner"),
    (817, "Consulting & Strategy", "Strategic Advantage"),
    (818, "Consulting & Strategy", "Guidance that Delivers"),
    (819, "Consulting & Strategy", "Simplifying Enterprise Change"),
    (820, "Consulting & Strategy", "Your Strategic Partner"),
    (821, "Enterprise Software", "Platforms That Perform"),
    (822, "Enterprise Software", "Business-Centric Code"),
    (823, "Enterprise Software", "Your Enterprise Engine"),
    (824, "Enterprise Software", "Software for Leaders"),
    (825, "Enterprise Software", "Smart Code, Smart Enterprise"),
    (826, "Enterprise Software", "Scaling Software Solutions"),
    (827, "Enterprise Software", "Enterprise Ready Tools"),
    (828, "Enterprise Software", "Systems That Scale"),
    (829, "Enterprise Software", "Enterprise First"),
    (830, "Enterprise Software", "Your Digital Core"),
    (831, "Enterprise Software", "Tech That Empowers"),
    (832, "Enterprise Software", "Enterprise Tools Simplified"),
    (833, "Enterprise Software", "Smart Solutions, Strong Software"),
    (834, "Enterprise Software", "Built for Enterprise Growth"),
    (835, "Enterprise Software", "Your Software Partner"),
    (836, "Enterprise Software", "Software with Strength"),
    (837, "Enterprise Software", "Performance That Powers"),
    (838, "Enterprise Software", "Smart Systems Edge"),
    (839, "Enterprise Software", "Enterprise Integration Partner"),
    (840, "Enterprise Software", "Code That Delivers"),
    (841, "Financial & Professional Services", "Finance for Enterprise Scale"),
    (842, "Financial & Professional Services", "Capital Confidence"),
    (843, "Financial & Professional Services", "Your Finance Engine"),
    (844, "Financial & Professional Services", "Enterprise Capital Simplified"),
    (845, "Financial & Professional Services", "Advisory that Scales"),
    (846, "Financial & Professional Services", "Finance Future-Ready"),
    (847, "Financial & Professional Services", "Smart Capital Advantage"),
    (848, "Financial & Professional Services", "Your Business Finance Partner"),
    (849, "Financial & Professional Services", "Secure Enterprise Finance"),
    (850, "Financial & Professional Services", "Partners for Growth"),
    (851, "Financial & Professional Services", "Finance with Strength"),
    (852, "Financial & Professional Services", "Advisory Edge for Business"),
    (853, "Financial & Professional Services", "Trusted Finance Services"),
    (854, "Financial & Professional Services", "Finance Made for Enterprise"),
    (855, "Financial & Professional Services", "Capital with Confidence"),
    (856, "Financial & Professional Services", "Smart Advisory Edge"),
    (857, "Financial & Professional Services", "Enterprise Finance Simplified"),
    (858, "Financial & Professional Services", "Advisory Beyond Borders"),
    (859, "Financial & Professional Services", "Smart Growth Finance"),
    (860, "Financial & Professional Services", "Your Finance Partner"),
    (861, "Logistics & Operations", "Smart Supply Chains"),
    (862, "Logistics & Operations", "Logistics that Scale"),
    (863, "Logistics & Operations", "Enterprise Supply Advantage"),
    (864, "Logistics & Operations", "Operations Without Limits"),
    (865, "Logistics & Operations", "Global Operations Edge"),
    (866, "Logistics & Operations", "Smart Logistics at Scale"),
    (867, "Logistics & Operations", "Logistics Made Enterprise-Ready"),
    (868, "Logistics & Operations", "Efficiency That Delivers"),
    (869, "Logistics & Operations", "Supply Chain Innovation"),
    (870, "Logistics & Operations", "Smart Shipping Systems"),
    (871, "Logistics & Operations", "Logistics Confidence"),
    (872, "Logistics & Operations", "Scale Logistics Simplified"),
    (873, "Logistics & Operations", "Enterprise-Grade Supply Chain"),
    (874, "Logistics & Operations", "Logistics That Work"),
    (875, "Logistics & Operations", "Global Scale Operations"),
    (876, "Logistics & Operations", "Your Logistics Edge"),
    (877, "Logistics & Operations", "Enterprise Logistics Simplified"),
    (878, "Logistics & Operations", "Smart Supply Partner"),
    (861, "Logistics & Operations", "Smart Supply Chains"),
    (862, "Logistics & Operations", "Logistics that Scale"),
    (863, "Logistics & Operations", "Enterprise Supply Advantage"),
    (864, "Logistics & Operations", "Operations Without Limits"),
    (865, "Logistics & Operations", "Global Operations Edge"),
    (866, "Logistics & Operations", "Smart Logistics at Scale"),
    (867, "Logistics & Operations", "Logistics Made Enterprise-Ready"),
    (868, "Logistics & Operations", "Efficiency That Delivers"),
    (869, "Logistics & Operations", "Supply Chain Innovation"),
    (870, "Logistics & Operations", "Smart Shipping Systems"),
    (871, "Logistics & Operations", "Logistics Confidence"),
    (872, "Logistics & Operations", "Scale Logistics Simplified"),
    (873, "Logistics & Operations", "Enterprise-Grade Supply Chain"),
    (874, "Logistics & Operations", "Logistics That Work"),
    (875, "Logistics & Operations", "Global Scale Operations"),
    (876, "Logistics & Operations", "Your Logistics Edge"),
    (877, "Logistics & Operations", "Enterprise Logistics Simplified"),
    (878, "Logistics & Operations", "Smart Supply Partner"),
    (879, "Logistics & Operations", "Operations You Can Trust"),
    (880, "Logistics & Operations", "Delivering Enterprise Success"),
    (881, "Enterprise Cloud & Security", "Enterprise-Grade Protection"),
    (882, "Enterprise Cloud & Security", "Your Data Fortress"),
    (883, "Enterprise Cloud & Security", "Security at Scale"),
    (884, "Enterprise Cloud & Security", "Business Continuity Simplified"),
    (885, "Enterprise Cloud & Security", "Cloud That Performs"),
    (886, "Enterprise Cloud & Security", "Protection Beyond Borders"),
    (887, "Enterprise Cloud & Security", "Enterprise Safe & Secure"),
    (888, "Enterprise Cloud & Security", "Smart Cloud Protection"),
    (889, "Enterprise Cloud & Security", "Secure the Enterprise Edge"),
    (890, "Enterprise Cloud & Security", "Your Defense in Depth"),
    (891, "Enterprise Cloud & Security", "Resilient Cloud Solutions"),
    (892, "Enterprise Cloud & Security", "Safe Business in the Cloud"),
    (893, "Enterprise Cloud & Security", "Protection That Scales"),
    (894, "Enterprise Cloud & Security", "Cloud Power. Business Confidence."),
    (895, "Enterprise Cloud & Security", "Enterprise Trust Delivered"),
    (896, "Enterprise Cloud & Security", "Safeguard Your Scale"),
    (897, "Enterprise Cloud & Security", "Enterprise Security Edge"),
    (898, "Enterprise Cloud & Security", "Built for Business Protection"),
    (899, "Enterprise Cloud & Security", "Cloud Defense Simplified"),
    (900, "Enterprise Cloud & Security", "Secure Future, Secure Growth"),
    (901, "Consulting & Strategy", "Smart Enterprise Guidance"),
    (902, "Consulting & Strategy", "Your Enterprise Navigator"),
    (903, "Consulting & Strategy", "Clarity for Corporations"),
    (904, "Consulting & Strategy", "Consulting Without Limits"),
    (905, "Consulting & Strategy", "Enterprise Insights Delivered"),
    (906, "Consulting & Strategy", "Future-Ready Consulting"),
    (907, "Consulting & Strategy", "Strategic Growth Simplified"),
    (908, "Consulting & Strategy", "Your Advisory Advantage"),
    (909, "Consulting & Strategy", "Trusted Enterprise Advisors"),
    (910, "Consulting & Strategy", "Advisory with Impact"),
    (911, "Consulting & Strategy", "Clarity that Scales"),
    (912, "Consulting & Strategy", "Your Growth Simplified"),
    (913, "Consulting & Strategy", "Partners in Transformation"),
    (914, "Consulting & Strategy", "Smart Change Advisory"),
    (915, "Consulting & Strategy", "Enterprise Guidance Edge"),
    (916, "Consulting & Strategy", "Scaling with Strategy"),
    (917, "Consulting & Strategy", "Enterprise Change Simplified"),
    (918, "Consulting & Strategy", "Your Path to Progress"),
    (919, "Consulting & Strategy", "Trusted by Enterprises"),
    (920, "Consulting & Strategy", "Advisory for the Modern Age"),
    (921, "Enterprise Software", "Enterprise Core Systems"),
    (922, "Enterprise Software", "Smart Code for Companies"),
    (923, "Enterprise Software", "Software at Scale"),
    (924, "Enterprise Software", "Your Digital Advantage"),
    (925, "Enterprise Software", "Enterprise Tools That Work"),
    (926, "Enterprise Software", "Scaling Business Seamlessly"),
    (927, "Enterprise Software", "Smart Platforms for Growth"),
    (928, "Enterprise Software", "Enterprise Systems Simplified"),
    (929, "Enterprise Software", "Business Tech That Delivers"),
    (930, "Enterprise Software", "Your Growth Engine"),
    (931, "Enterprise Software", "Software with Scale"),
    (932, "Enterprise Software", "Enterprise Digital Edge"),
    (933, "Enterprise Software", "Systems That Empower"),
    (934, "Enterprise Software", "Performance at Enterprise Level"),
    (935, "Enterprise Software", "Enterprise-First Tech"),
    (936, "Enterprise Software", "Your Business Code Partner"),
    (937, "Enterprise Software", "Software. Secure. Smart."),
    (938, "Enterprise Software", "Simplifying Business Scale"),
    (939, "Enterprise Software", "Enterprise Platforms that Perform"),
    (940, "Enterprise Software", "Smart Systems. Strong Results."),
    (941, "Financial & Professional Services", "Finance Built for Enterprise"),
    (942, "Financial & Professional Services", "Capital Confidence Edge"),
    (943, "Financial & Professional Services", "Trusted Finance Partners"),
    (944, "Financial & Professional Services", "Advisory in Action"),
    (945, "Financial & Professional Services", "Finance that Scales Up"),
    (946, "Financial & Professional Services", "Smart Finance for Growth"),
    (947, "Financial & Professional Services", "Enterprise Ready Advisory"),
    (948, "Financial & Professional Services", "Professional Finance Edge"),
    (949, "Financial & Professional Services", "Strong Capital, Strong Business"),
    (950, "Financial & Professional Services", "Your Finance Confidence Partner"),
    (951, "Financial & Professional Services", "Advisory that Delivers Results"),
    (952, "Financial & Professional Services", "Finance with Enterprise Strength"),
    (953, "Financial & Professional Services", "Smart Services for Scale"),
    (954, "Financial & Professional Services", "Advisory Simplified"),
    (955, "Financial & Professional Services", "Enterprise Capital Advantage"),
    (956, "Financial & Professional Services", "Confidence in Every Advisory"),
    (957, "Financial & Professional Services", "Finance That Matters"),
    (958, "Financial & Professional Services", "Enterprise-Grade Advisory"),
    (959, "Financial & Professional Services", "Smart Growth Partners"),
    (960, "Financial & Professional Services", "Your Finance Simplified"),
    (961, "Logistics & Operations", "Supply Chains That Scale"),
    (962, "Logistics & Operations", "Enterprise Logistics Edge"),
    (963, "Logistics & Operations", "Logistics Beyond Limits"),
    (964, "Logistics & Operations", "Operations for Growth"),
    (965, "Logistics & Operations", "Your Supply Advantage"),
    (966, "Logistics & Operations", "Smart Supply at Scale"),
    (967, "Logistics & Operations", "Enterprise Delivery Simplified"),
    (968, "Logistics & Operations", "Logistics Confidence Delivered"),
    (969, "Logistics & Operations", "Smart Supply Partners"),
    (970, "Logistics & Operations", "Scale with Logistics Strength"),
    (971, "Logistics & Operations", "Enterprise Operations Edge"),
    (972, "Logistics & Operations", "Global Supply. Local Success."),
    (973, "Logistics & Operations", "Smart Logistics Systems"),
    (974, "Logistics & Operations", "Your Enterprise Delivery Partner"),
    (975, "Logistics & Operations", "Logistics in Motion"),
    (976, "Logistics & Operations", "Supply Chain Strength Delivered"),
    (977, "Logistics & Operations", "Scaling Operations Seamlessly"),
    (978, "Logistics & Operations", "Smart Supply Edge"),
    (979, "Logistics & Operations", "Logistics That Scale"),
    (980, "Logistics & Operations", "Enterprise Logistics Confidence"),
    (981, "Enterprise Cloud & Security", "Enterprise Cloud Advantage"),
    (982, "Enterprise Cloud & Security", "Securing Business Growth"),
    (983, "Enterprise Cloud & Security", "Data Defense Simplified"),
    (984, "Enterprise Cloud & Security", "Business Security Partner"),
    (985, "Enterprise Cloud & Security", "Safe Cloud. Strong Business."),
    (986, "Enterprise Cloud & Security", "Enterprise Cloud Resilience"),
    (987, "Enterprise Cloud & Security", "Your Data Shield"),
    (988, "Enterprise Cloud & Security", "Secured for Scale"),
    (989, "Enterprise Cloud & Security", "Cloud Solutions You Can Trust"),
    (990, "Enterprise Cloud & Security", "Enterprise Security Evolution"),
    (991, "Enterprise Cloud & Security", "Cloud Power with Protection"),
    (992, "Enterprise Cloud & Security", "Business Security Simplified"),
    (993, "Enterprise Cloud & Security", "Enterprise Data Confidence"),
    (994, "Enterprise Cloud & Security", "Cloud Beyond Enterprise"),
    (995, "Enterprise Cloud & Security", "Protecting Enterprise Growth"),
    (996, "Enterprise Cloud & Security", "Safe and Scalable"),
    (997, "Enterprise Cloud & Security", "Your Security Partner in Cloud"),
    (998, "Enterprise Cloud & Security", "Enterprise Cloud Confidence"),
    (999, "Enterprise Cloud & Security", "Defend What Drives You"),
    (1000, "Enterprise Cloud & Security", "Security Without Limits"),
]
