from enum import StrEnum
from pydantic import Field
from pydantic.dataclasses import dataclass
from caseconverter import snakecase

"""
Based on data
- from https://consumergoods.com/top-100-consumer-goods-companies-2024
"""


class CompanyCategory(StrEnum):
    BEVERAGES = "beverages"
    FOOD_PRODUCTS = "food-products"
    HOUSEHOLD_DURABLES = "household-durables"
    HOUSEHOLD_PRODUCTS = "household-products"
    INTERACTIVE_MEDIA = "interactive-media-and-services"
    MISCELLANEOUS = "miscellaneous"
    PERSONAL_CARE = "personal-care"
    PHARMACEUTICALS = "pharmaceuticals"
    TEXTILES_APPAREL_LUXURY = "textiles-apparel-luxury"
    TOBACCO = "tobacco"


@dataclass
class CpgCompany:
    name: str
    revenue: float
    category: CompanyCategory
    alias: str
    products: list[str] = Field(default_factory=list)


@dataclass
class Product:
    name: str
    company: CpgCompany
    category: CompanyCategory
    alias: str
    weight: int


COMPANIES = [
    CpgCompany(
        rank=3,
        name="PepsiCo",
        revenue=91.471,
        category=CompanyCategory.BEVERAGES,
        alias="PEPSICO",
        products=[
            "Frito-Lay snacks (Lay’s, Doritos, Cheetos)",
            "Pepsi-Cola beverages",
            "Gatorade sports drinks",
            "Quaker Foods (cereals, oats)",
            "SodaStream (home carbonation)",
        ],
    ),
    CpgCompany(
        rank=7,
        name="Anheuser-Busch InBev",
        revenue=59.38,
        category=CompanyCategory.BEVERAGES,
        alias="ANHEUSER",
        products=["Budweiser", "Corona", "Stella Artois", "Michelob Ultra", "Beck’s"],
    ),
    CpgCompany(
        rank=10,
        name="Coca-Cola Co.",
        revenue=45.754,
        category=CompanyCategory.BEVERAGES,
        alias="COCACOLA",
        products=[
            "Coca-Cola (classic)",
            "Diet Coke",
            "Coca-Cola Zero Sugar",
            "Sprite",
            "Minute Maid juices",
        ],
    ),
    CpgCompany(
        rank=12,
        name="Heineken Holding N.V.",
        revenue=39.857,
        category=CompanyCategory.BEVERAGES,
        alias="HEINEKEN",
        products=["Heineken", "Amstel", "Sol", "Tiger Beer", "Desperados"],
    ),
    CpgCompany(
        rank=29,
        name="Diageo PLC",
        revenue=20.555,
        category=CompanyCategory.BEVERAGES,
        alias="DIAGEO",
        products=[
            "Johnnie Walker (whisky)",
            "Guinness (beer)",
            "Smirnoff (vodka)",
            "Baileys (liqueur)",
            "Tanqueray (gin)",
        ],
    ),
    CpgCompany(
        rank=35,
        name="Asahi Group Holdings",
        revenue=18.733,
        category=CompanyCategory.BEVERAGES,
        alias="ASAHI",
        products=[
            "Asahi Super Dry (beer)",
            "Calpis (soft drink)",
            "Mitsuya Cider (soft drink)",
            "Wilkinson (sparkling water)",
            "Nikka Whisky",
        ],
    ),
    CpgCompany(
        rank=46,
        name="Kirin Holdings",
        revenue=15.154,
        category=CompanyCategory.BEVERAGES,
        alias="KIRIN",
        products=[
            "Kirin Ichiban (beer)",
            "Kirin Lager",
            "Kirin Lemon (soft drink)",
            "Fire Coffee (ready-to-drink)",
            "Afternoon Tea (beverages)",
        ],
    ),
    CpgCompany(
        rank=48,
        name="Keurig Dr Pepper",
        revenue=14.814,
        category=CompanyCategory.BEVERAGES,
        alias="KEURIG",
        products=[
            "Dr Pepper",
            "7UP",
            "Snapple",
            "Keurig coffee systems & pods (Green Mountain)",
            "Canada Dry",
        ],
    ),
    CpgCompany(
        rank=54,
        name="Pernod Ricard",
        revenue=12.72,
        category=CompanyCategory.BEVERAGES,
        alias="PERNOD",
        products=[
            "Absolut Vodka",
            "Jameson Irish Whiskey",
            "Chivas Regal",
            "Beefeater Gin",
            "Martell Cognac",
        ],
    ),
    CpgCompany(
        rank=59,
        name="MolsonCoors Brewing Co.",
        revenue=11.702,
        category=CompanyCategory.BEVERAGES,
        alias="MOLSONCOORS",
        products=[
            "Coors Light",
            "Miller Lite",
            "Coors Banquet",
            "Molson Canadian / Carling",
            "Blue Moon / premium & value brands",
        ],
    ),
    CpgCompany(
        rank=63,
        name="Carlsberg A/S",
        revenue=10.685,
        category=CompanyCategory.BEVERAGES,
        alias="CARLSBERG",
        products=[
            "Carlsberg beer",
            "Tuborg",
            "Baltika",
            "Kronenbourg 1664",
            "Somersby cider",
        ],
    ),
    CpgCompany(
        rank=69,
        name="Constellation Brands",
        revenue=9.453,
        category=CompanyCategory.BEVERAGES,
        alias="CONSTELLATION",
        products=[
            "Corona Extra",
            "Modelo Especial",
            "Pacifico",
            "Robert Mondavi wines",
            "Svedka vodka",
        ],
    ),
    CpgCompany(
        rank=76,
        name="Thai Beverage Public Co.",
        revenue=8.415,
        category=CompanyCategory.BEVERAGES,
        alias="THAI_BEVERAGE",
        products=[
            "Chang Beer",
            "Mekhong (spirits)",
            "SangSom (rum)",
            "Oishi green tea",
            "est Cola",
        ],
    ),
    CpgCompany(
        rank=89,
        name="San Miguel Food & Beverage",
        revenue=6.754,
        category=CompanyCategory.BEVERAGES,
        alias="SAN_MIGUEL_FB",
        products=[
            "San Miguel Pale Pilsen",
            "Red Horse Beer",
            "Ginebra San Miguel (spirits)",
            "Magnolia (dairy & food products)",
            "Purefoods (processed meats)",
        ],
    ),
    CpgCompany(
        rank=1,
        name="Nestle SA",
        revenue=103.984,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="NESTLE",
        products=[
            "Nescafé",
            "Nespresso",
            "KitKat",
            "Purina pet food",
            "Nestlé Pure Life (water)",
        ],
    ),
    CpgCompany(
        rank=5,
        name="JBS S.A.",
        revenue=72.918,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="JBS",
        products=[
            "Beef products",
            "Pork products",
            "Chicken products",
            "Processed foods (Seara, Swift)",
            "Leather products",
        ],
    ),
    CpgCompany(
        rank=8,
        name="Tyson Foods",
        revenue=52.881,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="TYSON",
        products=[
            "Chicken",
            "Beef",
            "Pork",
            "Prepared foods (Jimmy Dean, Hillshire Farm)",
            "Ball Park (hot dogs)",
        ],
    ),
    CpgCompany(
        rank=15,
        name="Mondelez International",
        revenue=36.016,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="MONDELEZ",
        products=["Oreo", "Cadbury", "Milka", "Toblerone", "Trident gum"],
    ),
    CpgCompany(
        rank=19,
        name="Danone",
        revenue=29.892,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="DANONE",
        products=[
            "Activia (yogurt)",
            "Evian (water)",
            "Alpro (plant-based)",
            "Aptamil (infant formula)",
            "Nutricia (medical nutrition)",
        ],
    ),
    CpgCompany(
        rank=20,
        name="Kraft Heinz",
        revenue=26.64,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="KRAFT",
        products=[
            "Heinz Ketchup",
            "Kraft Mac & Cheese",
            "Oscar Mayer",
            "Philadelphia Cream Cheese",
            "Maxwell House coffee",
        ],
    ),
    CpgCompany(
        rank=23,
        name="Associated British Foods",
        revenue=24.233,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="ASSOCATED_BRITISH_FOODS",
        products=[
            "Twinings (tea)",
            "Ovaltine (malted drinks)",
            "Mazola (cooking oils)",
            "Kingsmill (bread)",
            "Primark (clothing retail)",
        ],
    ),
    CpgCompany(
        rank=26,
        name="Grupo Bimbo",
        revenue=22.85,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="GRUPO_BIMBO",
        products=[
            "Bimbo bread",
            "Marinela cakes & pastries",
            "Tía Rosa tortillas",
            "Oroweat / Arnold / Brownberry breads",
            "Barcel snacks (Takis)",
        ],
    ),
    CpgCompany(
        rank=31,
        name="General Mills",
        revenue=20.094,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="GENERAL_MILLS",
        products=[
            "Cheerios (cereal)",
            "Nature Valley (snacks)",
            "Blue Buffalo (pet food)",
            "Yoplait (yogurt)",
            "Old El Paso (Mexican foods)",
        ],
    ),
    CpgCompany(
        rank=37,
        name="Yili Group",
        revenue=17.612,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="YILI",
        products=[
            "Liquid milk",
            "Yogurt",
            "Ice cream",
            "Infant formula",
            "Milk powder",
        ],
    ),
    CpgCompany(
        rank=38,
        name="Kellogg Co.",
        revenue=16.46,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="KELLOGG",
        products=[
            "Corn Flakes",
            "Frosted Flakes",
            "Pringles",
            "Eggo waffles",
            "Special K",
        ],
    ),
    CpgCompany(
        rank=43,
        name="Fonterra Cooperative Group",
        revenue=15.32,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="FONTERRA",
        products=[
            "Anchor butter",
            "Anlene (nutrition milk)",
            "Anmum (maternal milk)",
            "Consumer cheeses",
            "Fresh dairy products",
        ],
    ),
    CpgCompany(
        rank=44,
        name="Uni-President Enterprises",
        revenue=15.205,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="UNI_PRESIDENT",
        products=[
            "Instant noodles",
            "Oishi beverages (tea & juice drinks)",
            "Dairy products",
            "Baked goods",
            "7-Eleven (convenience retail in Taiwan)",
        ],
    ),
    CpgCompany(
        rank=45,
        name="Arla Foods",
        revenue=15.199,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="ARLA",
        products=[
            "Lurpak (butter)",
            "Castello (cheese)",
            "Arla milk",
            "Skyr (yogurt)",
            "Baby&Me (infant nutrition)",
        ],
    ),
    CpgCompany(
        rank=49,
        name="Royal Friesland Campina N.V.",
        revenue=14.53,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="ROYAL_FRIESLAND",
        products=[
            "Friso (infant formula)",
            "Dutch Lady milk",
            "Campina dairy products",
            "Chocomel (chocolate milk)",
            "Frisian Flag (regional dairy brand)",
        ],
    ),
    CpgCompany(
        rank=52,
        name="China Mengniu Dairy Co.",
        revenue=13.891,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="CHINA_MENGNIU",
        products=[
            "Mengniu liquid milk",
            "Yogurt",
            "Ice cream",
            "Milk powder",
            "Yashili infant formula",
        ],
    ),
    CpgCompany(
        rank=53,
        name="Saputo, Inc.",
        revenue=13.234,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="SAPUTO",
        products=[
            "Cheese (mozzarella, cheddar, specialty)",
            "Milk",
            "Cream products",
            "Yogurt & dairy snacks",
            "Dairy ingredients (powder, whey)",
        ],
    ),
    CpgCompany(
        rank=56,
        name="Conagra Brands",
        revenue=12.277,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="CONAGRA",
        products=[
            "Healthy Choice (frozen meals)",
            "Hunt’s (sauces & tomatoes)",
            "Slim Jim (snacks)",
            "Birds Eye (frozen vegetables)",
            "Duncan Hines (desserts & baking)",
        ],
    ),
    CpgCompany(
        rank=57,
        name="Hormel Foods",
        revenue=12.11,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="HORMEL",
        products=[
            "Spam",
            "Skippy peanut butter",
            "Jennie-O turkey products",
            "Hormel chili & meats",
            "Planters nuts",
        ],
    ),
    CpgCompany(
        rank=61,
        name="Hershey Co.",
        revenue=11.165,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="HERSHEY",
        products=[
            "Hershey’s chocolate",
            "Reese’s",
            "KitKat (U.S.)",
            "Twizzlers",
            "Ice Breakers (mints & gum)",
        ],
    ),
    CpgCompany(
        rank=62,
        name="BRF - Brasil Foods",
        revenue=10.739,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="BRF",
        products=[
            "Sadia (processed meats)",
            "Perdigão (processed meats)",
            "Poultry",
            "Pork",
            "Frozen meals",
        ],
    ),
    CpgCompany(
        rank=65,
        name="First Pacific Co.",
        revenue=10.511,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="FIRST_PACIFIC",
        products=[
            "Indofood instant noodles",
            "Indofood seasonings & sauces",
            "Snack foods",
            "Dairy products",
            "Packaged cooking oils",
        ],
    ),
    CpgCompany(
        rank=67,
        name="Danish Crown",
        revenue=10.03,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="DANISH_CROWN",
        products=[
            "Pork products",
            "Beef products",
            "Processed meats (sausages, cold cuts)",
            "Ready meals",
            "Bacon",
        ],
    ),
    CpgCompany(
        rank=70,
        name="Campbell Soup Co.",
        revenue=9.357,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="CAMPBELL_SOUP",
        products=[
            "Campbell’s soups",
            "Pepperidge Farm (cookies, crackers)",
            "Goldfish (snacks)",
            "Prego (pasta sauces)",
            "V8 (juices)",
        ],
    ),
    CpgCompany(
        rank=74,
        name="NH Foods Ltd.",
        revenue=8.708,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="NH_FOODS",
        products=[
            "Ham & sausages",
            "Beef products",
            "Pork products",
            "Chicken products",
            "Seafood products",
        ],
    ),
    CpgCompany(
        rank=75,
        name="J.M. Smucker Co.",
        revenue=8.529,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="JM_SMUCKER",
        products=[
            "Smucker’s jams & jellies",
            "Jif peanut butter",
            "Folgers coffee",
            "Dunkin’ coffee (retail)",
            "Milk-Bone (pet snacks)",
        ],
    ),
    CpgCompany(
        rank=77,
        name="ITC Ltd.",
        revenue=8.375,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="ITC",
        products=[
            "Aashirvaad (flour & staples)",
            "Sunfeast (biscuits & snacks)",
            "Bingo! (snack foods)",
            "Classmate (stationery)",
            "ITC Hotels",
        ],
    ),
    CpgCompany(
        rank=83,
        name="Savencia SA",
        revenue=7.517,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="SAVENCIA",
        products=[
            "Caprice des Dieux (cheese)",
            "Saint Agur (blue cheese)",
            "Edelweiss (cheese spreads)",
            "Elle & Vire (dairy)",
            "Foodservice cheese products",
        ],
    ),
    CpgCompany(
        rank=86,
        name="Post Holdings",
        revenue=6.991,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="POST",
        products=[
            "Post cereals (Honey Bunches of Oats, Grape-Nuts)",
            "Weetabix",
            "Michael Foods (eggs & refrigerated products)",
            "Premier Protein (shakes & powders)",
            "Dymatize (sports nutrition)",
        ],
    ),
    CpgCompany(
        rank=92,
        name="McCormick & Co.",
        revenue=6.662,
        category=CompanyCategory.FOOD_PRODUCTS,
        alias="MCCORMICK",
        products=[
            "McCormick spices & herbs",
            "Lawry’s seasonings",
            "Frank’s RedHot sauce",
            "French’s mustard",
            "Old Bay seasoning",
        ],
    ),
    CpgCompany(
        rank=14,
        name="Haier Smart Home Co., Ltd.",
        revenue=36.529,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="HAIER",
        products=[
            "Refrigerators",
            "Washing machines",
            "Air conditioners",
            "Kitchen appliances",
            "Smart home IoT products",
        ],
    ),
    CpgCompany(
        rank=34,
        name="Whirlpool Corp.",
        revenue=19.455,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="WHIRLPOOL",
        products=[
            "Refrigerators",
            "Washing machines & dryers",
            "Dishwashers",
            "KitchenAid small appliances",
            "Microwaves & ovens",
        ],
    ),
    CpgCompany(
        rank=41,
        name="BSH Hausgeräte",
        revenue=15.433,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="HAUSGERATE",
        products=[
            "Bosch dishwashers",
            "Siemens washing machines",
            "Gaggenau ovens & cooktops",
            "Neff kitchen appliances",
            "Refrigerators & freezers",
        ],
    ),
    CpgCompany(
        rank=55,
        name="AB Electrolux",
        revenue=12.679,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="ELECTROLUX",
        products=[
            "Electrolux refrigerators",
            "Electrolux washing machines",
            "Vacuum cleaners",
            "Frigidaire kitchen appliances",
            "AEG ovens & cooktops",
        ],
    ),
    CpgCompany(
        rank=72,
        name="Groupe SEB",
        revenue=8.861,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="SEB",
        products=[
            "Tefal cookware",
            "Krups coffee machines",
            "Moulinex kitchen appliances",
            "Rowenta (irons, vacuums)",
            "All-Clad cookware",
        ],
    ),
    CpgCompany(
        rank=79,
        name="Newell Brands",
        revenue=8.133,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="NEWELL",
        products=[
            "Rubbermaid (storage & containers)",
            "Sharpie (writing instruments)",
            "Paper Mate (pens & pencils)",
            "Coleman (outdoor gear)",
            "Graco (baby products)",
        ],
    ),
    CpgCompany(
        rank=82,
        name="Arcelik A.S.",
        revenue=7.544,
        category=CompanyCategory.HOUSEHOLD_DURABLES,
        alias="ARCELIK",
        products=[
            "Refrigerators",
            "Washing machines",
            "Dishwashers",
            "Air conditioners",
            "Small household appliances",
        ],
    ),
    CpgCompany(
        rank=4,
        name="Procter & Gamble",
        revenue=82.006,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="PROCTOR_GAMBLE",
        products=[
            "Pampers (baby care)",
            "Tide / Ariel (laundry detergents)",
            "Gillette (razors & grooming)",
            "Pantene / Olay (beauty & haircare)",
            "Oral-B / Crest (oral care)",
        ],
    ),
    CpgCompany(
        rank=24,
        name="Henkel AG",
        revenue=23.285,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="HENKEL",
        products=[
            "Persil (laundry detergent)",
            "Schwarzkopf (hair care)",
            "Dial (personal care)",
            "Fa (body wash & deodorant)",
            "Loctite (consumer adhesives)",
        ],
    ),
    CpgCompany(
        rank=30,
        name="Kimberly-Clark Corp.",
        revenue=20.431,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="KIMBERLY_CLARK",
        products=[
            "Huggies (baby care)",
            "Kleenex (tissues)",
            "Cottonelle / Scott (toilet paper)",
            "Kotex (feminine care)",
            "Depend / Poise (adult care)",
        ],
    ),
    CpgCompany(
        rank=33,
        name="Colgate-Palmolive Co.",
        revenue=19.457,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="COLGATE_PALMOLIVE",
        products=[
            "Colgate toothpaste",
            "Palmolive dish soap",
            "Softsoap (hand & body wash)",
            "Hill’s Science Diet (pet food)",
            "Fabuloso / Ajax (household cleaners)",
        ],
    ),
    CpgCompany(
        rank=36,
        name="Reckitt Benckiser",
        revenue=18.647,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="RECKITT_BENCKISER",
        products=[
            "Lysol (disinfecting products)",
            "Dettol (antiseptic & hygiene)",
            "Durex (condoms)",
            "Enfamil (infant formula)",
            "Air Wick (air fresheners)",
        ],
    ),
    CpgCompany(
        rank=85,
        name="Clorox Co.",
        revenue=7.389,
        category=CompanyCategory.HOUSEHOLD_PRODUCTS,
        alias="CLOROX",
        products=[
            "Clorox bleach & disinfecting wipes",
            "Glad trash bags & food storage",
            "Fresh Step cat litter",
            "Burt’s Bees (personal care)",
            "Brita water filters",
        ],
    ),
    CpgCompany(
        rank=58,
        name="Nintendo Co.",
        revenue=11.852,
        category=CompanyCategory.INTERACTIVE_MEDIA,
        alias="NINTENDO",
        products=[
            "Nintendo Switch consoles",
            "Super Mario franchise",
            "The Legend of Zelda franchise",
            "Pokémon games & licensing",
            "Animal Crossing",
        ],
    ),
    CpgCompany(
        rank=84,
        name="Electronic Arts",
        revenue=7.426,
        category=CompanyCategory.INTERACTIVE_MEDIA,
        alias="EA",
        products=[
            "EA Sports FC (FIFA)",
            "Madden NFL",
            "The Sims",
            "Apex Legends",
            "Battlefield",
        ],
    ),
    CpgCompany(
        rank=88,
        name="Bandai Namco Holdings Inc.",
        revenue=6.822,
        category=CompanyCategory.INTERACTIVE_MEDIA,
        alias="BANDAI_NAMCO",
        products=[
            "Pac-Man & legacy games",
            "Tekken",
            "Dragon Ball games & licensing",
            "Gunpla (Gundam model kits)",
            "Tamagotchi",
        ],
    ),
    CpgCompany(
        rank=100,
        name="Mattel, Inc.",
        revenue=5.441,
        category=CompanyCategory.INTERACTIVE_MEDIA,
        alias="MATTEL",
        products=["Barbie", "Hot Wheels", "Fisher-Price", "American Girl", "UNO"],
    ),
    CpgCompany(
        rank=18,
        name="3M Co.",
        revenue=32.681,
        category=CompanyCategory.MISCELLANEOUS,
        alias="THREE_M",
        products=[
            "Post-it Notes",
            "Scotch tape & adhesives",
            "Command hooks",
            "Nexcare bandages",
            "Filtrete air filters",
        ],
    ),
    CpgCompany(
        rank=21,
        name="WH Group Ltd.",
        revenue=26.236,
        category=CompanyCategory.MISCELLANEOUS,
        alias="WH_GROUP",
        products=[
            "Pork products (Smithfield, Shuanghui)",
            "Processed meats (ham, bacon, sausages)",
            "Frozen packaged foods",
            "Canned meats",
            "Seasoned fresh pork",
        ],
    ),
    CpgCompany(
        rank=40,
        name="Stanley Black & Decker",
        revenue=15.781,
        category=CompanyCategory.MISCELLANEOUS,
        alias="STANLEY_BD",
        products=[
            "Stanley hand tools",
            "DeWalt power tools",
            "Craftsman tools",
            "Black+Decker appliances",
            "Outdoor equipment",
        ],
    ),
    CpgCompany(
        rank=81,
        name="Masco Corporation",
        revenue=7.967,
        category=CompanyCategory.MISCELLANEOUS,
        alias="MASCO",
        products=[
            "Behr paint",
            "Delta faucets",
            "Hansgrohe fixtures",
            "KraftMaid cabinets",
            "Milgard windows & doors",
        ],
    ),
    CpgCompany(
        rank=6,
        name="Unilever N.V.",
        revenue=64.509,
        category=CompanyCategory.PERSONAL_CARE,
        alias="UNILEVER",
        products=[
            "Dove (personal care)",
            "Axe / Lynx (deodorants)",
            "Hellmann’s (foods)",
            "Ben & Jerry’s (ice cream)",
            "Magnum (ice cream)",
        ],
    ),
    CpgCompany(
        rank=11,
        name="L’Oréal",
        revenue=44.572,
        category=CompanyCategory.PERSONAL_CARE,
        alias="LOREAL",
        products=[
            "L’Oréal Paris (cosmetics & skincare)",
            "Lancôme",
            "Maybelline",
            "Kiehl’s",
            "Garnier",
        ],
    ),
    CpgCompany(
        rank=39,
        name="Estée Lauder Companies",
        revenue=15.91,
        category=CompanyCategory.PERSONAL_CARE,
        alias="ESTEE",
        products=["Estée Lauder", "Clinique", "MAC Cosmetics", "La Mer", "Bobbi Brown"],
    ),
    CpgCompany(
        rank=50,
        name="Essity",
        revenue=14.436,
        category=CompanyCategory.PERSONAL_CARE,
        alias="ESSITY",
        products=[
            "TENA (adult incontinence products)",
            "Tork (tissues & hygiene products)",
            "Libresse / Bodyform (feminine care)",
            "Tempo (tissues)",
            "Vinda (household paper in Asia)",
        ],
    ),
    CpgCompany(
        rank=51,
        name="Haleon",
        revenue=14.059,
        category=CompanyCategory.PERSONAL_CARE,
        alias="HALEON",
        products=[
            "Sensodyne (toothpaste)",
            "Centrum (vitamins)",
            "Panadol (pain relief)",
            "Voltaren (topical pain gel)",
            "Theraflu (cold & flu)",
        ],
    ),
    CpgCompany(
        rank=64,
        name="Kao Corp.",
        revenue=10.54,
        category=CompanyCategory.PERSONAL_CARE,
        alias="KAO",
        products=[
            "Biore (skincare)",
            "Kanebo (cosmetics)",
            "Attack (laundry detergent)",
            "Merries (baby diapers)",
            "John Frieda (haircare)",
        ],
    ),
    CpgCompany(
        rank=66,
        name="Beiersdorf AG",
        revenue=10.453,
        category=CompanyCategory.PERSONAL_CARE,
        alias="BEIERSDORF",
        products=[
            "Nivea (skincare)",
            "Eucerin (dermatological skincare)",
            "La Prairie (luxury skincare)",
            "Labello (lip care)",
            "Hansaplast (wound care)",
        ],
    ),
    CpgCompany(
        rank=87,
        name="Shiseido Co.",
        revenue=6.867,
        category=CompanyCategory.PERSONAL_CARE,
        alias="SHISEIDO",
        products=[
            "Shiseido (skincare & cosmetics)",
            "Clé de Peau Beauté",
            "NARS (makeup)",
            "Anessa (suncare)",
            "Senka (mass skincare)",
        ],
    ),
    CpgCompany(
        rank=91,
        name="Unicharm Corp.",
        revenue=6.687,
        category=CompanyCategory.PERSONAL_CARE,
        alias="UNICHARM",
        products=[
            "MamyPoko (baby diapers)",
            "Moony (baby care)",
            "Sofy (feminine care)",
            "Lifree (adult incontinence)",
            "Pet care products (Unicharm Pet)",
        ],
    ),
    CpgCompany(
        rank=97,
        name="Church & Dwight Co., Inc.",
        revenue=5.868,
        category=CompanyCategory.PERSONAL_CARE,
        alias="CHURCH_DWIGHT",
        products=[
            "Arm & Hammer (household & oral care)",
            "Trojan (condoms)",
            "First Response (pregnancy tests)",
            "OXICLEAN (cleaning products)",
            "Nair (hair removal)",
        ],
    ),
    CpgCompany(
        rank=99,
        name="Coty, Inc.",
        revenue=5.554,
        category=CompanyCategory.PERSONAL_CARE,
        alias="COTY",
        products=[
            "CoverGirl",
            "Rimmel",
            "Sally Hansen",
            "Calvin Klein fragrances",
            "Gucci Beauty (licensed fragrances & cosmetics)",
        ],
    ),
    CpgCompany(
        rank=42,
        name="Johnson & Johnson Consumer Health",
        revenue=15.4,
        category=CompanyCategory.PHARMACEUTICALS,
        alias="JOHNSON_JOHNSON",
        products=[
            "Neutrogena (skincare)",
            "Aveeno (skincare)",
            "Listerine (oral care)",
            "Tylenol (OTC pain relief)",
            "Johnson’s Baby",
        ],
    ),
    CpgCompany(
        rank=78,
        name="Abbott - Nutrition",
        revenue=8.154,
        category=CompanyCategory.PHARMACEUTICALS,
        alias="ABBOTT",
        products=[
            "Ensure (adult nutrition)",
            "Similac (infant formula)",
            "Pedialyte (oral rehydration)",
            "Glucerna (diabetes nutrition)",
            "PediaSure (children’s nutrition)",
        ],
    ),
    CpgCompany(
        rank=90,
        name="Bayer Consumer Health",
        revenue=6.699,
        category=CompanyCategory.PHARMACEUTICALS,
        alias="BAYER",
        products=[
            "Aspirin",
            "Claritin (allergy relief)",
            "Alka-Seltzer",
            "One A Day (vitamins)",
            "Canesten (antifungal)",
        ],
    ),
    CpgCompany(
        rank=2,
        name="LVMH Moet Hennessy Louis Vuitton",
        revenue=94.444,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="LVMH",
        products=[
            "Louis Vuitton (fashion & leather goods)",
            "Dior (fashion, fragrance, cosmetics)",
            "Moët & Chandon (champagne)",
            "Hennessy (cognac)",
            "Sephora (beauty retail)",
        ],
    ),
    CpgCompany(
        rank=9,
        name="Nike, Inc.",
        revenue=51.217,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="NIKE",
        products=[
            "Footwear (Nike Air, Air Jordan)",
            "Apparel (sportswear, training gear)",
            "Converse",
            "Accessories & equipment",
            "Nike digital/connected fitness",
        ],
    ),
    CpgCompany(
        rank=25,
        name="Adidas AG",
        revenue=23.19,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="ADIDAS",
        products=[
            "Footwear (Ultraboost, Superstar, Originals)",
            "Apparel (athletic & lifestyle)",
            "Reebok (heritage brand)",
            "Accessories (bags, caps, socks)",
            "Collaborations (Yeezy, designer lines)",
        ],
    ),
    CpgCompany(
        rank=27,
        name="Kering",
        revenue=21.176,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="KERING",
        products=[
            "Gucci",
            "Saint Laurent",
            "Bottega Veneta",
            "Balenciaga",
            "Alexander McQueen",
        ],
    ),
    CpgCompany(
        rank=28,
        name="Richemont",
        revenue=20.779,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="RICHEMONT",
        products=[
            "Cartier (jewelry & watches)",
            "Van Cleef & Arpels",
            "Montblanc",
            "Piaget",
            "IWC Schaffhausen",
        ],
    ),
    CpgCompany(
        rank=47,
        name="Hermes International",
        revenue=15.019,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="HERMES",
        products=[
            "Leather goods (Birkin, Kelly bags)",
            "Silk scarves",
            "Ready-to-wear & accessories",
            "Fragrances",
            "Watches & jewelry",
        ],
    ),
    CpgCompany(
        rank=60,
        name="VF Corp.",
        revenue=11.612,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="VF",
        products=["The North Face", "Vans", "Timberland", "Dickies", "Supreme"],
    ),
    CpgCompany(
        rank=68,
        name="Puma",
        revenue=9.521,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="PUMA",
        products=[
            "Footwear (running, lifestyle, training)",
            "Apparel (sportswear & fashion)",
            "Accessories (bags, hats, socks)",
            "Collaborations (Fenty, celebrities/designers)",
            "Motorsport collections",
        ],
    ),
    CpgCompany(
        rank=71,
        name="PVH Corp.",
        revenue=9.024,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="PVH",
        products=[
            "Calvin Klein",
            "Tommy Hilfiger",
            "Heritage brands (Van Heusen, IZOD)",
            "Underwear & intimate apparel",
            "Casualwear & accessories",
        ],
    ),
    CpgCompany(
        rank=73,
        name="Swatch Group AG",
        revenue=8.786,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="SWATCH",
        products=["Swatch watches", "Omega", "Longines", "Tissot", "Breguet"],
    ),
    CpgCompany(
        rank=80,
        name="Skechers",
        revenue=8.0,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="SKECHERS",
        products=[
            "Performance footwear (running, walking)",
            "Casual footwear",
            "Kids’ footwear",
            "Work & safety shoes",
            "Apparel & accessories",
        ],
    ),
    CpgCompany(
        rank=93,
        name="Tapestry, Inc.",
        revenue=6.661,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="TAPESTRY",
        products=[
            "Coach (handbags & leather goods)",
            "Kate Spade (handbags & lifestyle)",
            "Stuart Weitzman (footwear)",
            "Accessories (wallets, belts, small leather goods)",
            "Apparel & outerwear",
        ],
    ),
    CpgCompany(
        rank=94,
        name="Ralph Lauren Corp.",
        revenue=6.444,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="RALPH_LAUREN",
        products=[
            "Polo Ralph Lauren (menswear & womenswear)",
            "Ralph Lauren Collection",
            "Footwear & accessories",
            "Home (bedding, furnishings, décor)",
            "Fragrances",
        ],
    ),
    CpgCompany(
        rank=95,
        name="Levi Strauss",
        revenue=6.179,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="LEVISTRAUSS",
        products=[
            "Levi’s jeans & denim apparel",
            "Dockers (casual apparel)",
            "Denizen (value denim line)",
            "Signature by Levi Strauss (mass market denim)",
            "Tops & jackets",
        ],
    ),
    CpgCompany(
        rank=96,
        name="Under Armour",
        revenue=5.904,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="UNDERARMOR",
        products=[
            "Performance apparel (training, running, basketball)",
            "Footwear (running, basketball, training)",
            "Accessories (bags, gloves, caps)",
            "Connected fitness (apps & wearables)",
            "Athleisure apparel",
        ],
    ),
    CpgCompany(
        rank=98,
        name="Hanesbrands Inc.",
        revenue=5.637,
        category=CompanyCategory.TEXTILES_APPAREL_LUXURY,
        alias="HANESBRANDS",
        products=[
            "Hanes (underwear & basics)",
            "Champion (athletic apparel)",
            "Bali (intimates)",
            "Maidenform (intimates)",
            "Playtex (bras & lingerie)",
        ],
    ),
    CpgCompany(
        rank=13,
        name="Imperial Tobacco Group",
        revenue=39.847,
        category=CompanyCategory.TOBACCO,
        alias="IMPERIAL_TOBACCO",
        products=[
            "Davidoff (cigarettes)",
            "Gauloises Blondes",
            "West",
            "Golden Virginia (roll-your-own tobacco)",
            "Blu (e-cigarettes/vaping)",
        ],
    ),
    CpgCompany(
        rank=16,
        name="Philip Morris International",
        revenue=35.174,
        category=CompanyCategory.TOBACCO,
        alias="PHILIP_MORRIS",
        products=[
            "Marlboro",
            "IQOS (heated tobacco)",
            "L&M",
            "Chesterfield",
            "Parliament",
        ],
    ),
    CpgCompany(
        rank=17,
        name="British American Tobacco PLC",
        revenue=33.937,
        category=CompanyCategory.TOBACCO,
        alias="BRITISH_AMERICAN_TOBACCO",
        products=[
            "Dunhill",
            "Lucky Strike",
            "Pall Mall",
            "Rothmans",
            "Vuse (vaping products)",
        ],
    ),
    CpgCompany(
        rank=22,
        name="Altria Group",
        revenue=24.483,
        category=CompanyCategory.TOBACCO,
        alias="ALTRIA",
        products=[
            "Marlboro (U.S. rights)",
            "Copenhagen (smokeless tobacco)",
            "Skoal (smokeless tobacco)",
            "Black & Mild (cigars)",
            "On! (oral nicotine pouches)",
        ],
    ),
    CpgCompany(
        rank=32,
        name="Japan Tobacco, Inc.",
        revenue=19.59,
        category=CompanyCategory.TOBACCO,
        alias="JAPAN_TOBACCO",
        products=[
            "Mevius",
            "Winston",
            "Camel (Japan rights)",
            "LD",
            "Logic (vaping/e-cigarettes)",
        ],
    ),
]
