from enum import StrEnum


class Country(StrEnum):
    INDIA = "India"
    CHINA = "China"
    UNITED_STATES = "United States"
    INDONESIA = "Indonesia"
    PAKISTAN = "Pakistan"
    NIGERIA = "Nigeria"
    BRAZIL = "Brazil"
    BANGALDESH = "Bangladesh"
    RUSSIA = "Russia"
    MEXICO = "Mexico"
    JAPAN = "Japan"
    PHILIPPINES = "Philippines"
    ETHIOPIA = "Ethiopia"
    CONGO = "Democratic Republic of the Congo"
    EGYPT = "Egypt"
    VIETNAM = "Vietnam"
    IRAN = "Iran"
    TURKEY = "Turkey"
    GERMANY = "Germany"
    FRANCE = "France"
    UNITED_KINGDOM = "United Kingdom"
    TANZANIA = "Tanzania"
    THAILAND = "Thailand"
    SOUTH_AFRICA = "South Africa"
    ITALY = "Italy"
    COLOMBIA = "Colombia"
    KENYA = "Kenya"
    MYANMAR = "Myanmar"
    SOUTH_KOREA = "South Korea"
    SUDAN = "Sudan"
